import type { BodyRegion, Exercise, MovementPattern } from './types'

type CatalogEntry = {
  id: string
  name: string
  family: string
  aliases?: string[]
  pattern: MovementPattern
  regions: BodyRegion[]
  primaryRegion: BodyRegion
  equipment: string[]
  description: string
  roleTags: string[]
}

const movement = (entry: CatalogEntry): Exercise => ({
  ...entry,
  aliases: entry.aliases ?? [],
  favorite: false,
  jointFeeling: 'neutral'
})

// This catalog is original ForgePath taxonomy informed by public strength and
// hypertrophy principles. It does not reproduce a competitor's proprietary list.
export const expandedExercises: Exercise[] = [
  // Squat, quadriceps, and unilateral lower body
  movement({ id: 'high-bar-squat', name: 'High-Bar Back Squat', family: 'Squat', aliases: ['High Bar Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates'], description: 'Upright back-squat variation with a strong quadriceps contribution.', roleTags: ['strength', 'hypertrophy', 'quads', 'squat'] }),
  movement({ id: 'low-bar-squat', name: 'Low-Bar Back Squat', family: 'Squat', aliases: ['Low Bar Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes', 'hamstrings', 'trunk'], primaryRegion: 'glutes', equipment: ['barbell', 'rack', 'plates'], description: 'Hip-dominant back-squat variation used for strength specificity and overload.', roleTags: ['strength anchor', 'competition', 'squat'] }),
  movement({ id: 'front-squat', name: 'Front Squat', family: 'Squat', pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk', 'back'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates'], description: 'Anterior-loaded squat for quadriceps, trunk, and upper-back strength.', roleTags: ['secondary builder', 'quads', 'upper back'] }),
  movement({ id: 'paused-squat', name: 'Paused Back Squat', family: 'Squat', aliases: ['Pause Squat', 'Pause in the Hole Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates'], description: 'Back squat paused at depth to build position and strength out of the hole.', roleTags: ['secondary builder', 'out of the hole', 'strength'] }),
  movement({ id: 'tempo-squat', name: 'Tempo Back Squat', family: 'Squat', aliases: ['Slow Eccentric Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates'], description: 'Back squat with a standardized eccentric tempo for control and time under tension.', roleTags: ['technique', 'hypertrophy', 'position'] }),
  movement({ id: 'box-squat', name: 'Box Squat', family: 'Squat', pattern: 'squat', regions: ['glutes', 'quadriceps', 'hamstrings', 'trunk'], primaryRegion: 'glutes', equipment: ['barbell', 'rack', 'box', 'plates'], description: 'Squat to a repeatable box height for posterior-chain and starting-strength emphasis.', roleTags: ['secondary builder', 'posterior chain', 'starting strength'] }),
  movement({ id: 'pin-squat', name: 'Pin Squat', family: 'Squat', aliases: ['Anderson Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates'], description: 'Dead-start squat from safeties for position-specific force production.', roleTags: ['secondary builder', 'starting strength', 'weak point'] }),
  movement({ id: 'cambered-bar-squat', name: 'Cambered Bar Squat', family: 'Specialty-Bar Squat', pattern: 'squat', regions: ['quadriceps', 'glutes', 'back', 'trunk'], primaryRegion: 'quadriceps', equipment: ['cambered bar', 'rack', 'plates'], description: 'Specialty-bar squat that challenges trunk and upper-back control.', roleTags: ['secondary builder', 'upper back', 'specialty bar'] }),
  movement({ id: 'buffalo-bar-squat', name: 'Buffalo Bar Squat', family: 'Specialty-Bar Squat', aliases: ['Bow Bar Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['buffalo bar', 'rack', 'plates'], description: 'Curved-bar squat option that can reduce shoulder demand while preserving squat loading.', roleTags: ['strength', 'joint friendly', 'specialty bar'] }),
  movement({ id: 'belt-squat', name: 'Belt Squat', family: 'Machine Squat', pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['belt squat machine'], description: 'Axially unloaded squat pattern for high-output leg work with less upper-body demand.', roleTags: ['hypertrophy', 'quads', 'low fatigue', 'secondary builder'] }),
  movement({ id: 'pendulum-squat', name: 'Pendulum Squat', family: 'Machine Squat', pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['pendulum squat machine'], description: 'Supported machine squat with a stable arc and high quadriceps stimulus.', roleTags: ['hypertrophy', 'quads', 'machine', 'low fatigue'] }),
  movement({ id: 'v-squat', name: 'V-Squat Machine', family: 'Machine Squat', aliases: ['V Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['v-squat machine'], description: 'Guided squat machine for stable quadriceps and glute loading.', roleTags: ['hypertrophy', 'quads', 'machine'] }),
  movement({ id: 'smith-squat', name: 'Smith Machine Squat', family: 'Machine Squat', aliases: ['Smith Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['smith machine'], description: 'Fixed-path squat variation that reduces balance demand and supports repeatable setup.', roleTags: ['hypertrophy', 'quads', 'machine'] }),
  movement({ id: 'leg-press-45', name: '45-Degree Leg Press', family: 'Leg Press', aliases: ['Leg Press', 'Incline Leg Press', 'Sled Leg Press'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['leg press machine'], description: 'Stable sled press for high-output quadriceps and glute work with low coordination demand.', roleTags: ['hypertrophy', 'quads', 'machine', 'low fatigue', 'squat alternative'] }),
  movement({ id: 'horizontal-leg-press', name: 'Horizontal Leg Press', family: 'Leg Press', aliases: ['Seated Leg Press'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['horizontal leg press machine'], description: 'Seated horizontal press for stable lower-body loading and straightforward setup.', roleTags: ['hypertrophy', 'quads', 'machine', 'low fatigue'] }),
  movement({ id: 'single-leg-press', name: 'Single-Leg Press', family: 'Leg Press', aliases: ['Unilateral Leg Press'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['leg press machine'], description: 'Unilateral sled press for side-to-side leg work with a stable external path.', roleTags: ['hypertrophy', 'quads', 'unilateral', 'machine'] }),
  movement({ id: 'squat-press', name: 'Squat Press', family: 'Leg Press', aliases: ['Cybex Squat Press', 'Cybex Plate-Loaded Squat Press', 'Side Deck Squat Press'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['squat press machine'], description: 'Plate-loaded squat press for stable, high-output quadriceps and glute work with less balance demand than a free-weight squat.', roleTags: ['strength', 'hypertrophy', 'quads', 'machine', 'low fatigue', 'squat alternative', 'secondary builder', 'home gym'] }),
  movement({ id: 'goblet-squat', name: 'Goblet Squat', family: 'Squat', pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['dumbbells'], description: 'Front-loaded dumbbell squat for accessible leg training and short setup.', roleTags: ['hypertrophy', 'short setup', 'travel', 'quads'] }),
  movement({ id: 'bulgarian-split-squat', name: 'Rear-Foot-Elevated Split Squat', family: 'Split Squat', aliases: ['Bulgarian Split Squat', 'RFESS'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['dumbbells', 'bench'], description: 'Unilateral squat for quadriceps and glutes with a long, adjustable range.', roleTags: ['hypertrophy', 'unilateral', 'quads', 'secondary builder'] }),
  movement({ id: 'front-foot-elevated-split-squat', name: 'Front-Foot-Elevated Split Squat', family: 'Split Squat', aliases: ['FFE Split Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['dumbbells', 'step'], description: 'Split squat using front-foot elevation to increase usable range of motion.', roleTags: ['hypertrophy', 'unilateral', 'lengthened'] }),
  movement({ id: 'walking-lunge', name: 'Walking Lunge', family: 'Lunge', pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['dumbbells'], description: 'Alternating forward lunge for unilateral leg volume and locomotor control.', roleTags: ['hypertrophy', 'unilateral', 'conditioning'] }),
  movement({ id: 'reverse-lunge', name: 'Reverse Lunge', family: 'Lunge', pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'glutes', equipment: ['dumbbells'], description: 'Backward-stepping lunge with adjustable torso and shin positions.', roleTags: ['hypertrophy', 'unilateral', 'glutes'] }),
  movement({ id: 'step-up', name: 'Dumbbell Step-Up', family: 'Step-Up', aliases: ['Step Up'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'glutes', equipment: ['dumbbells', 'box'], description: 'Unilateral box ascent for leg strength and glute-focused work.', roleTags: ['hypertrophy', 'unilateral', 'glutes'] }),
  movement({ id: 'leg-extension', name: 'Leg Extension', family: 'Knee Extension', aliases: ['Machine Leg Extension', 'Freak Athlete Leg Developer Leg Extension', 'Hyper Pro Leg Extension'], pattern: 'isolation', regions: ['quadriceps'], primaryRegion: 'quadriceps', equipment: ['leg extension machine'], description: 'Stable knee-extension isolation for direct quadriceps work, including the Freak Athlete Leg Developer setup.', roleTags: ['accessory', 'quadriceps', 'machine', 'low fatigue', 'home gym'] }),
  movement({ id: 'single-leg-extension', name: 'Single-Leg Extension', family: 'Knee Extension', aliases: ['Unilateral Leg Extension', 'Freak Athlete Single-Leg Extension'], pattern: 'isolation', regions: ['quadriceps'], primaryRegion: 'quadriceps', equipment: ['leg extension machine'], description: 'Unilateral knee extension for direct quadriceps work and side-to-side tracking, including the Freak Athlete Leg Developer setup.', roleTags: ['accessory', 'quadriceps', 'unilateral', 'machine', 'home gym'] }),
  movement({ id: 'reverse-nordic', name: 'Reverse Nordic Curl', family: 'Knee Extension', aliases: ['Reverse Nordic'], pattern: 'isolation', regions: ['quadriceps'], primaryRegion: 'quadriceps', equipment: ['bodyweight'], description: 'Bodyweight knee-extension pattern that loads the quadriceps through a long muscle length.', roleTags: ['accessory', 'quadriceps', 'bodyweight', 'lengthened'] }),

  // Deadlift, hamstrings, glutes, and posterior chain
  movement({ id: 'conventional-deadlift', name: 'Conventional Deadlift', family: 'Deadlift', aliases: ['Conventional Deads'], pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back', 'trunk'], primaryRegion: 'hamstrings', equipment: ['barbell', 'plates'], description: 'Conventional-stance deadlift for whole posterior-chain strength.', roleTags: ['strength anchor', 'competition', 'hinge'] }),
  movement({ id: 'romanian-deadlift', name: 'Romanian Deadlift', family: 'Deadlift', aliases: ['RDL'], pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back'], primaryRegion: 'hamstrings', equipment: ['barbell', 'plates'], description: 'Controlled hip hinge for hamstrings, glutes, and deadlift midrange strength.', roleTags: ['secondary builder', 'hamstrings', 'hypertrophy', 'midrange'] }),
  movement({ id: 'stiff-leg-deadlift', name: 'Stiff-Leg Deadlift', family: 'Deadlift', aliases: ['SLDL', 'Stiff Leg Deadlift'], pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back'], primaryRegion: 'hamstrings', equipment: ['barbell', 'plates'], description: 'Long-range hinge that emphasizes hamstrings and spinal erectors.', roleTags: ['secondary builder', 'hamstrings', 'off floor'] }),
  movement({ id: 'trap-bar-deadlift', name: 'Trap Bar Deadlift', family: 'Deadlift', aliases: ['Hex Bar Deadlift'], pattern: 'hinge', regions: ['quadriceps', 'glutes', 'hamstrings', 'back'], primaryRegion: 'glutes', equipment: ['trap bar', 'plates'], description: 'Centered-load deadlift variation with adjustable leg and hip contribution.', roleTags: ['strength', 'secondary builder', 'joint friendly'] }),
  movement({ id: 'paused-conventional-deadlift', name: 'Paused Conventional Deadlift', family: 'Deadlift', aliases: ['Pause Deadlift'], pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back', 'trunk'], primaryRegion: 'hamstrings', equipment: ['barbell', 'plates'], description: 'Conventional deadlift paused below the knee for off-floor position and control.', roleTags: ['secondary builder', 'off floor', 'technique'] }),
  movement({ id: 'halting-deadlift', name: 'Halting Deadlift', family: 'Deadlift', pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back', 'trunk'], primaryRegion: 'hamstrings', equipment: ['barbell', 'plates'], description: 'Deadlift variation emphasizing controlled work below the knee before completing the lift.', roleTags: ['secondary builder', 'off floor', 'time under tension'] }),
  movement({ id: 'block-pull', name: 'Block Pull', family: 'Deadlift', aliases: ['Deadlift from Blocks'], pattern: 'hinge', regions: ['glutes', 'back', 'hamstrings'], primaryRegion: 'glutes', equipment: ['barbell', 'plates', 'blocks'], description: 'Reduced-range deadlift from blocks for lockout strength and overload.', roleTags: ['secondary builder', 'lockout', 'overload'] }),
  movement({ id: 'rack-pull', name: 'Rack Pull', family: 'Deadlift', pattern: 'hinge', regions: ['glutes', 'back', 'hamstrings'], primaryRegion: 'back', equipment: ['barbell', 'rack', 'plates'], description: 'Deadlift from safeties for range-specific back and lockout strength.', roleTags: ['secondary builder', 'lockout', 'overload'] }),
  movement({ id: 'snatch-grip-deadlift', name: 'Snatch-Grip Deadlift', family: 'Deadlift', pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back', 'trunk'], primaryRegion: 'back', equipment: ['barbell', 'plates'], description: 'Wide-grip deadlift that increases range and upper-back demand.', roleTags: ['secondary builder', 'upper back', 'long range'] }),
  movement({ id: 'sumo-block-pull', name: 'Sumo Block Pull', family: 'Deadlift', pattern: 'hinge', regions: ['glutes', 'quadriceps', 'back'], primaryRegion: 'glutes', equipment: ['barbell', 'plates', 'blocks'], description: 'Reduced-range sumo pull for lockout overload and position-specific strength.', roleTags: ['secondary builder', 'sumo', 'lockout', 'overload'] }),
  movement({ id: 'banded-deadlift', name: 'Banded Deadlift', family: 'Deadlift', pattern: 'hinge', regions: ['glutes', 'hamstrings', 'back', 'trunk'], primaryRegion: 'glutes', equipment: ['barbell', 'plates', 'bands'], description: 'Deadlift with ascending band resistance for acceleration and lockout demand.', roleTags: ['secondary builder', 'accommodating resistance', 'lockout'] }),
  movement({ id: 'chain-deadlift', name: 'Chain Deadlift', family: 'Deadlift', pattern: 'hinge', regions: ['glutes', 'hamstrings', 'back', 'trunk'], primaryRegion: 'glutes', equipment: ['barbell', 'plates', 'chains'], description: 'Deadlift with progressive chain loading across the range of motion.', roleTags: ['secondary builder', 'accommodating resistance', 'overload'] }),
  movement({ id: 'barbell-good-morning', name: 'Barbell Good Morning', family: 'Good Morning', pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back', 'trunk'], primaryRegion: 'hamstrings', equipment: ['barbell', 'rack', 'plates'], description: 'Barbell hinge for posterior-chain and trunk strength.', roleTags: ['secondary builder', 'posterior chain'] }),
  movement({ id: 'ssb-good-morning', name: 'Safety Squat Bar Good Morning', family: 'Good Morning', aliases: ['SSB Good Morning'], pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back', 'trunk'], primaryRegion: 'hamstrings', equipment: ['safety squat bar', 'rack', 'plates'], description: 'Specialty-bar good morning with substantial upper-back and trunk demand.', roleTags: ['secondary builder', 'posterior chain', 'specialty bar'] }),
  movement({ id: 'dumbbell-rdl', name: 'Dumbbell Romanian Deadlift', family: 'Deadlift', aliases: ['Dumbbell RDL'], pattern: 'hinge', regions: ['hamstrings', 'glutes'], primaryRegion: 'hamstrings', equipment: ['dumbbells'], description: 'Dumbbell hinge for accessible hamstring and glute loading.', roleTags: ['hypertrophy', 'hamstrings', 'short setup'] }),
  movement({ id: 'single-leg-rdl', name: 'Single-Leg Romanian Deadlift', family: 'Deadlift', aliases: ['Single Leg RDL'], pattern: 'hinge', regions: ['hamstrings', 'glutes'], primaryRegion: 'hamstrings', equipment: ['dumbbells'], description: 'Unilateral hinge for hamstrings, glutes, and side-to-side control.', roleTags: ['hypertrophy', 'unilateral', 'hamstrings'] }),
  movement({ id: 'staggered-stance-rdl', name: 'Staggered-Stance Romanian Deadlift', family: 'Deadlift', aliases: ['B-Stance RDL'], pattern: 'hinge', regions: ['hamstrings', 'glutes'], primaryRegion: 'hamstrings', equipment: ['dumbbells'], description: 'Supported unilateral hinge for hamstring loading with reduced balance demand.', roleTags: ['hypertrophy', 'unilateral', 'hamstrings'] }),
  movement({ id: 'barbell-hip-thrust', name: 'Barbell Hip Thrust', family: 'Hip Extension', aliases: ['Hip Thrust'], pattern: 'hinge', regions: ['glutes', 'hamstrings'], primaryRegion: 'glutes', equipment: ['barbell', 'bench', 'plates'], description: 'Loaded hip extension with high glute output and limited spinal range.', roleTags: ['hypertrophy', 'glutes', 'low fatigue'] }),
  movement({ id: 'glute-bridge', name: 'Barbell Glute Bridge', family: 'Hip Extension', pattern: 'hinge', regions: ['glutes', 'hamstrings'], primaryRegion: 'glutes', equipment: ['barbell', 'plates'], description: 'Floor-based hip extension for direct glute loading.', roleTags: ['hypertrophy', 'glutes', 'short setup'] }),
  movement({ id: 'cable-pull-through', name: 'Cable Pull-Through', family: 'Hip Extension', pattern: 'hinge', regions: ['glutes', 'hamstrings'], primaryRegion: 'glutes', equipment: ['cable station', 'rope'], description: 'Cable hinge with a stable resistance line and modest systemic fatigue.', roleTags: ['accessory', 'glutes', 'low fatigue'] }),
  movement({ id: 'back-extension-45', name: '45-Degree Back Extension', family: 'Back Extension', aliases: ['45 Degree Back Raise'], pattern: 'hinge', regions: ['hamstrings', 'glutes', 'back'], primaryRegion: 'hamstrings', equipment: ['back extension bench'], description: 'Supported posterior-chain extension with adjustable hamstring, glute, and back emphasis.', roleTags: ['accessory', 'posterior chain', 'low fatigue'] }),
  movement({ id: 'reverse-hyper', name: 'Reverse Hyperextension', family: 'Back Extension', aliases: ['Reverse Hyper'], pattern: 'hinge', regions: ['glutes', 'hamstrings', 'back'], primaryRegion: 'glutes', equipment: ['reverse hyper machine'], description: 'Supported hip extension for glutes, hamstrings, and lower-back training.', roleTags: ['accessory', 'posterior chain', 'machine'] }),
  movement({ id: 'lying-leg-curl', name: 'Lying Leg Curl', family: 'Leg Curl', aliases: ['Prone Leg Curl', 'Freak Athlete Leg Developer Hamstring Curl', 'Hyper Pro Hamstring Curl'], pattern: 'isolation', regions: ['hamstrings'], primaryRegion: 'hamstrings', equipment: ['lying leg curl machine'], description: 'Prone knee-flexion isolation for direct hamstring work, including the Freak Athlete Leg Developer setup.', roleTags: ['accessory', 'hamstrings', 'machine', 'home gym', 'low fatigue'] }),
  movement({ id: 'standing-leg-curl', name: 'Standing Single-Leg Curl', family: 'Leg Curl', aliases: ['Standing Leg Curl'], pattern: 'isolation', regions: ['hamstrings'], primaryRegion: 'hamstrings', equipment: ['standing leg curl machine'], description: 'Unilateral standing knee-flexion isolation for hamstrings.', roleTags: ['accessory', 'hamstrings', 'unilateral', 'machine'] }),
  movement({ id: 'nordic-curl', name: 'Nordic Hamstring Curl', family: 'Leg Curl', aliases: ['Nordic Curl'], pattern: 'isolation', regions: ['hamstrings'], primaryRegion: 'hamstrings', equipment: ['bodyweight', 'nordic bench'], description: 'Bodyweight eccentric-focused knee flexion for hamstring strength.', roleTags: ['accessory', 'hamstrings', 'lengthened'] }),
  movement({ id: 'glute-ham-raise', name: 'Glute-Ham Raise', family: 'Leg Curl', aliases: ['GHR'], pattern: 'isolation', regions: ['hamstrings', 'glutes'], primaryRegion: 'hamstrings', equipment: ['glute ham developer'], description: 'Combined knee-flexion and hip-extension movement for hamstrings and glutes.', roleTags: ['accessory', 'hamstrings', 'posterior chain'] }),

  // Bench press, chest, and triceps builders
  movement({ id: 'close-grip-bench', name: 'Close-Grip Bench Press', family: 'Bench Press', aliases: ['CGBP'], pattern: 'horizontal-push', regions: ['triceps', 'chest', 'shoulders'], primaryRegion: 'triceps', equipment: ['barbell', 'bench', 'rack'], description: 'Narrower-grip bench variation for triceps and lockout strength.', roleTags: ['secondary builder', 'triceps', 'lockout'] }),
  movement({ id: 'wide-grip-bench', name: 'Wide-Grip Bench Press', family: 'Bench Press', pattern: 'horizontal-push', regions: ['chest', 'shoulders', 'triceps'], primaryRegion: 'chest', equipment: ['barbell', 'bench', 'rack'], description: 'Wide-grip bench variation for chest-specific strength and range practice.', roleTags: ['secondary builder', 'chest', 'off chest'] }),
  movement({ id: 'spoto-press', name: 'Spoto Press', family: 'Bench Press', pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['barbell', 'bench', 'rack'], description: 'Bench press paused just above the chest for control and midrange strength.', roleTags: ['secondary builder', 'off chest', 'midrange'] }),
  movement({ id: 'larsen-press', name: 'Larsen Press', family: 'Bench Press', aliases: ['Feet-Up Bench Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['barbell', 'bench', 'rack'], description: 'Bench press without leg drive for chest strength and repeatable upper-body loading.', roleTags: ['secondary builder', 'chest', 'hypertrophy'] }),
  movement({ id: 'floor-press', name: 'Barbell Floor Press', family: 'Bench Press', aliases: ['Floor Press'], pattern: 'horizontal-push', regions: ['triceps', 'chest', 'shoulders'], primaryRegion: 'triceps', equipment: ['barbell', 'rack', 'plates'], description: 'Reduced-range press from the floor for triceps and midrange strength.', roleTags: ['secondary builder', 'triceps', 'lockout'] }),
  movement({ id: 'one-board-press', name: 'One-Board Press', family: 'Bench Press', aliases: ['1 Board Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['barbell', 'bench', 'rack', 'boards'], description: 'Slightly reduced-range bench variation for off-chest and midrange strength.', roleTags: ['secondary builder', 'midrange', 'bench'] }),
  movement({ id: 'pin-press', name: 'Bench Pin Press', family: 'Bench Press', aliases: ['Dead Bench'], pattern: 'horizontal-push', regions: ['triceps', 'chest', 'shoulders'], primaryRegion: 'triceps', equipment: ['barbell', 'bench', 'rack'], description: 'Dead-start bench press from safeties for range-specific force production.', roleTags: ['secondary builder', 'starting strength', 'weak point'] }),
  movement({ id: 'cambered-bar-bench', name: 'Cambered Bar Bench Press', family: 'Bench Press', aliases: ['Cambered Bar Press'], pattern: 'horizontal-push', regions: ['chest', 'shoulders', 'triceps'], primaryRegion: 'chest', equipment: ['cambered bar', 'bench', 'rack'], description: 'Specialty-bar bench with additional range and chest loading.', roleTags: ['secondary builder', 'long range', 'specialty bar'] }),
  movement({ id: 'swiss-bar-bench', name: 'Swiss Bar Bench Press', family: 'Bench Press', aliases: ['Football Bar Bench'], pattern: 'horizontal-push', regions: ['triceps', 'chest', 'shoulders'], primaryRegion: 'triceps', equipment: ['swiss bar', 'bench', 'rack'], description: 'Neutral-grip specialty-bar bench for triceps and shoulder-compatible pressing.', roleTags: ['secondary builder', 'triceps', 'joint friendly', 'specialty bar'] }),
  movement({ id: 'banded-bench', name: 'Banded Bench Press', family: 'Bench Press', pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'triceps', equipment: ['barbell', 'bench', 'rack', 'bands'], description: 'Bench press with ascending band resistance for acceleration and lockout demand.', roleTags: ['secondary builder', 'accommodating resistance', 'lockout'] }),
  movement({ id: 'chain-bench', name: 'Chain Bench Press', family: 'Bench Press', pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'triceps', equipment: ['barbell', 'bench', 'rack', 'chains'], description: 'Bench press with progressive chain loading through the range.', roleTags: ['secondary builder', 'accommodating resistance', 'overload'] }),
  movement({ id: 'incline-barbell-press', name: 'Incline Barbell Bench Press', family: 'Incline Press', aliases: ['Incline Bench Press'], pattern: 'horizontal-push', regions: ['chest', 'shoulders', 'triceps'], primaryRegion: 'chest', equipment: ['barbell', 'adjustable bench', 'rack'], description: 'Incline barbell press for upper-chest and anterior-shoulder strength.', roleTags: ['strength', 'hypertrophy', 'upper chest'] }),
  movement({ id: 'decline-barbell-press', name: 'Decline Barbell Bench Press', family: 'Bench Press', aliases: ['Decline Bench Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps'], primaryRegion: 'chest', equipment: ['barbell', 'decline bench', 'rack'], description: 'Decline press for chest and triceps with a shorter pressing range.', roleTags: ['strength', 'hypertrophy', 'chest'] }),
  movement({ id: 'flat-db-press', name: 'Flat Dumbbell Bench Press', family: 'Bench Press', aliases: ['Dumbbell Bench Press'], pattern: 'horizontal-push', regions: ['chest', 'shoulders', 'triceps'], primaryRegion: 'chest', equipment: ['dumbbells', 'bench'], description: 'Dumbbell bench press with independent arm paths for chest hypertrophy.', roleTags: ['hypertrophy', 'chest', 'short setup'] }),
  movement({ id: 'decline-db-press', name: 'Decline Dumbbell Press', family: 'Bench Press', pattern: 'horizontal-push', regions: ['chest', 'triceps'], primaryRegion: 'chest', equipment: ['dumbbells', 'decline bench'], description: 'Decline dumbbell press for stable chest and triceps volume.', roleTags: ['hypertrophy', 'chest'] }),
  movement({ id: 'machine-chest-press', name: 'Machine Chest Press', family: 'Machine Press', aliases: ['Seated Chest Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['chest press machine'], description: 'Stable machine press for chest work with low coordination demand.', roleTags: ['hypertrophy', 'chest', 'machine', 'low fatigue'] }),
  movement({ id: 'plate-loaded-chest-press', name: 'Plate-Loaded Chest Press', family: 'Machine Press', aliases: ['Hammer Strength Chest Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['plate-loaded chest press'], description: 'Plate-loaded converging press for stable chest and triceps loading.', roleTags: ['hypertrophy', 'chest', 'machine'] }),
  movement({ id: 'smith-bench-press', name: 'Smith Machine Bench Press', family: 'Machine Press', aliases: ['Smith Bench Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['smith machine', 'bench'], description: 'Fixed-path bench press for repeatable chest loading and low balance demand.', roleTags: ['hypertrophy', 'chest', 'machine'] }),
  movement({ id: 'push-up', name: 'Push-Up', family: 'Push-Up', aliases: ['Pushup'], pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['bodyweight'], description: 'Bodyweight horizontal press with scalable range and loading.', roleTags: ['hypertrophy', 'bodyweight', 'short setup'] }),
  movement({ id: 'deficit-push-up', name: 'Deficit Push-Up', family: 'Push-Up', pattern: 'horizontal-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['bodyweight', 'push-up handles'], description: 'Elevated-hand push-up that increases chest range of motion.', roleTags: ['hypertrophy', 'bodyweight', 'lengthened'] }),
  movement({ id: 'pec-deck', name: 'Pec Deck Fly', family: 'Chest Fly', aliases: ['Machine Fly'], pattern: 'isolation', regions: ['chest'], primaryRegion: 'chest', equipment: ['pec deck machine'], description: 'Stable machine adduction for direct chest work.', roleTags: ['accessory', 'chest', 'machine', 'low fatigue'] }),
  movement({ id: 'dumbbell-fly', name: 'Dumbbell Fly', family: 'Chest Fly', pattern: 'isolation', regions: ['chest'], primaryRegion: 'chest', equipment: ['dumbbells', 'bench'], description: 'Free-weight chest fly with a standardized bench angle and range.', roleTags: ['accessory', 'chest', 'lengthened'] }),
  movement({ id: 'cable-press-around', name: 'Cable Press-Around', family: 'Chest Fly', aliases: ['Single-Arm Cable Fly'], pattern: 'isolation', regions: ['chest'], primaryRegion: 'chest', equipment: ['cable station'], description: 'Single-arm cable adduction that maintains tension through a long arc.', roleTags: ['accessory', 'chest', 'short setup'] }),

  // Back, lats, and upper back
  movement({ id: 'barbell-row', name: 'Bent-Over Barbell Row', family: 'Row', aliases: ['Barbell Row'], pattern: 'horizontal-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['barbell', 'plates'], description: 'Unsupported barbell row for back strength and hinge-position tolerance.', roleTags: ['strength', 'back', 'secondary builder'] }),
  movement({ id: 'pendlay-row', name: 'Pendlay Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['barbell', 'plates'], description: 'Dead-start barbell row for upper-back force and deadlift support.', roleTags: ['secondary builder', 'upper back', 'deadlift'] }),
  movement({ id: 'seal-row', name: 'Seal Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['barbell', 'seal row bench'], description: 'Prone-supported barbell row that removes low-back loading.', roleTags: ['hypertrophy', 'back', 'low fatigue'] }),
  movement({ id: 't-bar-row', name: 'T-Bar Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['t-bar row machine'], description: 'Loaded row with a fixed pivot for upper-back and lat work.', roleTags: ['hypertrophy', 'back', 'machine'] }),
  movement({ id: 'one-arm-db-row', name: 'One-Arm Dumbbell Row', family: 'Row', aliases: ['Single-Arm Dumbbell Row'], pattern: 'horizontal-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['dumbbells', 'bench'], description: 'Unilateral dumbbell row with adjustable torso support and elbow path.', roleTags: ['hypertrophy', 'back', 'unilateral'] }),
  movement({ id: 'meadows-row', name: 'Meadows Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['landmine', 'barbell', 'plates'], description: 'One-arm landmine row for lats and upper back through a diagonal path.', roleTags: ['hypertrophy', 'back', 'unilateral'] }),
  movement({ id: 'seated-cable-row', name: 'Seated Cable Row', family: 'Row', aliases: ['Cable Row'], pattern: 'horizontal-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['cable station', 'row handle'], description: 'Stable cable row for repeatable back loading.', roleTags: ['hypertrophy', 'back', 'low fatigue'] }),
  movement({ id: 'single-arm-cable-row', name: 'Single-Arm Cable Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['cable station', 'single handle'], description: 'Unilateral cable row with a flexible path for lat or upper-back emphasis.', roleTags: ['hypertrophy', 'back', 'unilateral'] }),
  movement({ id: 'wide-grip-machine-row', name: 'Wide-Grip Machine Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps', 'shoulders'], primaryRegion: 'back', equipment: ['row machine'], description: 'Supported wide-elbow row for upper-back and rear-shoulder work.', roleTags: ['hypertrophy', 'upper back', 'machine', 'low fatigue'] }),
  movement({ id: 'pull-up', name: 'Pull-Up', family: 'Vertical Pull', aliases: ['Pronated Pull-Up'], pattern: 'vertical-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['pull-up bar'], description: 'Bodyweight vertical pull with a pronated grip.', roleTags: ['strength', 'lats', 'bodyweight'] }),
  movement({ id: 'chin-up', name: 'Chin-Up', family: 'Vertical Pull', aliases: ['Supinated Pull-Up'], pattern: 'vertical-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['pull-up bar'], description: 'Supinated-grip vertical pull for lats and elbow flexors.', roleTags: ['strength', 'lats', 'biceps', 'bodyweight'] }),
  movement({ id: 'assisted-pull-up', name: 'Assisted Pull-Up', family: 'Vertical Pull', pattern: 'vertical-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['assisted pull-up machine'], description: 'Counterbalanced vertical pull for scalable lat and upper-back work.', roleTags: ['hypertrophy', 'lats', 'machine'] }),
  movement({ id: 'wide-grip-pulldown', name: 'Wide-Grip Lat Pulldown', family: 'Vertical Pull', pattern: 'vertical-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['cable station', 'pulldown bar'], description: 'Pronated wide-grip pulldown for lats and upper back.', roleTags: ['hypertrophy', 'lats', 'upper back'] }),
  movement({ id: 'underhand-pulldown', name: 'Underhand Lat Pulldown', family: 'Vertical Pull', aliases: ['Supinated Pulldown'], pattern: 'vertical-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['cable station', 'pulldown bar'], description: 'Supinated cable pulldown for lats and biceps.', roleTags: ['hypertrophy', 'lats', 'biceps'] }),
  movement({ id: 'single-arm-pulldown', name: 'Single-Arm Lat Pulldown', family: 'Vertical Pull', pattern: 'vertical-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['cable station', 'single handle'], description: 'Unilateral cable pulldown with an adjustable elbow path.', roleTags: ['hypertrophy', 'lats', 'unilateral'] }),
  movement({ id: 'straight-arm-pulldown', name: 'Straight-Arm Pulldown', family: 'Pullover', aliases: ['Cable Pullover'], pattern: 'isolation', regions: ['back'], primaryRegion: 'back', equipment: ['cable station', 'rope'], description: 'Shoulder-extension isolation for lats with minimal elbow-flexor demand.', roleTags: ['accessory', 'lats', 'low fatigue'] }),
  movement({ id: 'machine-pullover', name: 'Pullover Machine', family: 'Pullover', aliases: ['Machine Pullover'], pattern: 'isolation', regions: ['back'], primaryRegion: 'back', equipment: ['pullover machine'], description: 'Stable shoulder-extension machine for direct lat work.', roleTags: ['accessory', 'lats', 'machine', 'low fatigue'] }),
  movement({ id: 'dumbbell-pullover', name: 'Dumbbell Pullover', family: 'Pullover', pattern: 'isolation', regions: ['back', 'chest'], primaryRegion: 'back', equipment: ['dumbbells', 'bench'], description: 'Dumbbell shoulder-extension movement for lats with chest involvement.', roleTags: ['accessory', 'lats', 'lengthened'] }),
  movement({ id: 'barbell-shrug', name: 'Barbell Shrug', family: 'Shrug', pattern: 'carry', regions: ['traps', 'forearms'], primaryRegion: 'traps', equipment: ['barbell', 'plates'], description: 'Loaded scapular elevation for direct upper-trapezius work and grip.', roleTags: ['accessory', 'traps', 'grip'] }),
  movement({ id: 'dumbbell-shrug', name: 'Dumbbell Shrug', family: 'Shrug', aliases: ['DB Shrug'], pattern: 'carry', regions: ['traps', 'forearms'], primaryRegion: 'traps', equipment: ['dumbbells'], description: 'Independent dumbbell scapular elevation for direct upper-trapezius work with minimal setup.', roleTags: ['accessory', 'traps', 'grip', 'short setup'] }),
  movement({ id: 'trap-bar-shrug', name: 'Trap Bar Shrug', family: 'Shrug', aliases: ['Hex Bar Shrug'], pattern: 'carry', regions: ['traps', 'forearms'], primaryRegion: 'traps', equipment: ['trap bar', 'plates'], description: 'Neutral-grip scapular elevation that supports heavy upper-trapezius loading.', roleTags: ['accessory', 'traps', 'grip', 'overload'] }),
  movement({ id: 'cable-shrug', name: 'Cable Shrug', family: 'Shrug', pattern: 'carry', regions: ['traps', 'forearms'], primaryRegion: 'traps', equipment: ['cable station', 'straight bar attachment'], description: 'Cable-loaded scapular elevation for direct upper-trapezius work through a consistent line of pull.', roleTags: ['accessory', 'traps', 'grip', 'low fatigue'] }),
  movement({ id: 'machine-shrug', name: 'Machine Shrug', family: 'Shrug', aliases: ['Plate-Loaded Shrug'], pattern: 'carry', regions: ['traps', 'forearms'], primaryRegion: 'traps', equipment: ['shrug machine'], description: 'Stable machine scapular elevation for repeatable upper-trapezius loading.', roleTags: ['accessory', 'traps', 'machine', 'low fatigue'] }),
  movement({ id: 'chest-supported-db-shrug', name: 'Chest-Supported Dumbbell Shrug', family: 'Shrug', aliases: ['Incline Bench Shrug', 'Kelso Dumbbell Shrug'], pattern: 'horizontal-pull', regions: ['traps', 'back'], primaryRegion: 'traps', equipment: ['dumbbells', 'adjustable bench'], description: 'Chest-supported scapular retraction on an incline bench for direct middle-trapezius work with low trunk demand.', roleTags: ['accessory', 'traps', 'mid traps', 'chest supported', 'low fatigue'] }),

  // Shoulders
  movement({ id: 'seated-barbell-press', name: 'Seated Barbell Overhead Press', family: 'Overhead Press', aliases: ['Seated OHP'], pattern: 'vertical-push', regions: ['shoulders', 'triceps'], primaryRegion: 'shoulders', equipment: ['barbell', 'adjustable bench', 'rack'], description: 'Supported barbell overhead press for shoulder and triceps strength.', roleTags: ['strength', 'shoulders', 'secondary builder'] }),
  movement({ id: 'seated-db-press', name: 'Seated Dumbbell Shoulder Press', family: 'Overhead Press', aliases: ['Dumbbell Shoulder Press'], pattern: 'vertical-push', regions: ['shoulders', 'triceps'], primaryRegion: 'shoulders', equipment: ['dumbbells', 'adjustable bench'], description: 'Supported dumbbell press with independent arm paths.', roleTags: ['hypertrophy', 'shoulders'] }),
  movement({ id: 'machine-shoulder-press', name: 'Machine Shoulder Press', family: 'Machine Press', pattern: 'vertical-push', regions: ['shoulders', 'triceps'], primaryRegion: 'shoulders', equipment: ['shoulder press machine'], description: 'Stable machine press for shoulder and triceps volume.', roleTags: ['hypertrophy', 'shoulders', 'machine', 'low fatigue'] }),
  movement({ id: 'arnold-press', name: 'Arnold Press', family: 'Overhead Press', pattern: 'vertical-push', regions: ['shoulders', 'triceps'], primaryRegion: 'shoulders', equipment: ['dumbbells', 'adjustable bench'], description: 'Rotating dumbbell press through a long shoulder range.', roleTags: ['hypertrophy', 'shoulders'] }),
  movement({ id: 'landmine-press', name: 'Half-Kneeling Landmine Press', family: 'Landmine Press', aliases: ['Landmine Press'], pattern: 'vertical-push', regions: ['shoulders', 'triceps', 'trunk'], primaryRegion: 'shoulders', equipment: ['landmine', 'barbell', 'plates'], description: 'Angled unilateral press for shoulders and trunk with a shoulder-compatible path.', roleTags: ['hypertrophy', 'joint friendly', 'unilateral'] }),
  movement({ id: 'push-press', name: 'Push Press', family: 'Overhead Press', pattern: 'vertical-push', regions: ['shoulders', 'triceps', 'quadriceps', 'trunk'], primaryRegion: 'shoulders', equipment: ['barbell', 'rack', 'plates'], description: 'Leg-assisted overhead press for power and overload.', roleTags: ['power', 'overload', 'strength'] }),
  movement({ id: 'db-lateral-raise', name: 'Dumbbell Lateral Raise', family: 'Lateral Raise', pattern: 'isolation', regions: ['shoulders'], primaryRegion: 'shoulders', equipment: ['dumbbells'], description: 'Dumbbell abduction for direct side-deltoid work.', roleTags: ['accessory', 'lateral delts', 'short setup'] }),
  movement({ id: 'machine-lateral-raise', name: 'Machine Lateral Raise', family: 'Lateral Raise', pattern: 'isolation', regions: ['shoulders'], primaryRegion: 'shoulders', equipment: ['lateral raise machine'], description: 'Stable machine abduction for direct side-deltoid work.', roleTags: ['accessory', 'lateral delts', 'machine', 'low fatigue'] }),
  movement({ id: 'leaning-cable-lateral-raise', name: 'Leaning Cable Lateral Raise', family: 'Lateral Raise', pattern: 'isolation', regions: ['shoulders'], primaryRegion: 'shoulders', equipment: ['cable station', 'single handle'], description: 'Leaning single-arm cable raise for side-deltoid loading through a long arc.', roleTags: ['accessory', 'lateral delts', 'lengthened'] }),
  movement({ id: 'reverse-pec-deck', name: 'Reverse Pec Deck', family: 'Rear Delt Fly', aliases: ['Reverse Fly Machine'], pattern: 'isolation', regions: ['shoulders', 'back'], primaryRegion: 'shoulders', equipment: ['pec deck machine'], description: 'Supported reverse fly for rear deltoids and upper back.', roleTags: ['accessory', 'rear delts', 'machine', 'low fatigue'] }),
  movement({ id: 'cable-rear-delt-fly', name: 'Cable Rear-Delt Fly', family: 'Rear Delt Fly', aliases: ['Cable Reverse Fly'], pattern: 'isolation', regions: ['shoulders', 'back'], primaryRegion: 'shoulders', equipment: ['cable station'], description: 'Cable horizontal abduction for rear deltoids and upper back.', roleTags: ['accessory', 'rear delts'] }),
  movement({ id: 'face-pull', name: 'Cable Face Pull', family: 'Rear Delt Pull', aliases: ['Face Pull'], pattern: 'horizontal-pull', regions: ['shoulders', 'traps', 'back'], primaryRegion: 'shoulders', equipment: ['cable station', 'rope'], description: 'High cable row and external-rotation pattern for rear shoulders, trapezius, and upper back.', roleTags: ['accessory', 'rear delts', 'upper back', 'traps', 'low fatigue'] }),
  movement({ id: 'upright-row', name: 'Cable Upright Row', family: 'Upright Row', pattern: 'vertical-pull', regions: ['shoulders', 'traps', 'biceps'], primaryRegion: 'shoulders', equipment: ['cable station', 'straight bar attachment'], description: 'Cable vertical row for side deltoids and upper traps.', roleTags: ['accessory', 'lateral delts', 'traps'] }),

  // Arms
  movement({ id: 'triceps-pushdown', name: 'Cable Triceps Pushdown', family: 'Triceps Extension', aliases: ['Triceps Pressdown'], pattern: 'isolation', regions: ['triceps'], primaryRegion: 'triceps', equipment: ['cable station', 'rope'], description: 'Cable elbow extension for direct triceps work.', roleTags: ['accessory', 'triceps', 'short setup', 'low fatigue'] }),
  movement({ id: 'ez-bar-skull-crusher', name: 'EZ-Bar Skull Crusher', family: 'Triceps Extension', aliases: ['Lying Triceps Extension'], pattern: 'isolation', regions: ['triceps'], primaryRegion: 'triceps', equipment: ['ez bar', 'bench', 'plates'], description: 'Lying elbow extension for direct triceps loading.', roleTags: ['accessory', 'triceps', 'lengthened'] }),
  movement({ id: 'db-skull-crusher', name: 'Dumbbell Skull Crusher', family: 'Triceps Extension', aliases: ['DB Skullcrusher'], pattern: 'isolation', regions: ['triceps'], primaryRegion: 'triceps', equipment: ['dumbbells', 'bench'], description: 'Dumbbell lying extension with independent arm paths.', roleTags: ['accessory', 'triceps', 'lengthened'] }),
  movement({ id: 'rolling-db-extension', name: 'Rolling Dumbbell Triceps Extension', family: 'Triceps Extension', aliases: ['Rolling DB Extension'], pattern: 'isolation', regions: ['triceps'], primaryRegion: 'triceps', equipment: ['dumbbells', 'bench'], description: 'Hybrid extension and press for triceps size and strength.', roleTags: ['accessory', 'triceps', 'secondary builder'] }),
  movement({ id: 'jm-press', name: 'JM Press', family: 'Bench Press', pattern: 'horizontal-push', regions: ['triceps', 'chest'], primaryRegion: 'triceps', equipment: ['barbell', 'bench', 'rack'], description: 'Bench-extension hybrid for heavy triceps training and lockout support.', roleTags: ['secondary builder', 'triceps', 'lockout'] }),
  movement({ id: 'parallel-bar-dip', name: 'Parallel-Bar Dip', family: 'Dip', aliases: ['Chest Dip', 'Triceps Dip'], pattern: 'vertical-push', regions: ['triceps', 'chest', 'shoulders'], primaryRegion: 'triceps', equipment: ['dip station'], description: 'Bodyweight press for triceps and chest with scalable added load.', roleTags: ['strength', 'hypertrophy', 'bodyweight'] }),
  movement({ id: 'assisted-dip', name: 'Assisted Dip', family: 'Dip', pattern: 'vertical-push', regions: ['triceps', 'chest', 'shoulders'], primaryRegion: 'triceps', equipment: ['assisted dip machine'], description: 'Counterbalanced dip for scalable triceps and chest work.', roleTags: ['hypertrophy', 'triceps', 'machine'] }),
  movement({ id: 'barbell-curl', name: 'Barbell Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps', 'forearms'], primaryRegion: 'biceps', equipment: ['barbell', 'plates'], description: 'Standing barbell elbow flexion for biceps strength and size.', roleTags: ['accessory', 'biceps', 'strength'] }),
  movement({ id: 'ez-bar-curl', name: 'EZ-Bar Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps', 'forearms'], primaryRegion: 'biceps', equipment: ['ez bar', 'plates'], description: 'Angled-grip curl for repeatable biceps and forearm loading.', roleTags: ['accessory', 'biceps'] }),
  movement({ id: 'incline-db-curl', name: 'Incline Dumbbell Curl', family: 'Curl', aliases: ['Incline Curl'], pattern: 'isolation', regions: ['biceps'], primaryRegion: 'biceps', equipment: ['dumbbells', 'adjustable bench'], description: 'Incline-supported curl that trains the biceps at a long muscle length.', roleTags: ['accessory', 'biceps', 'lengthened'] }),
  movement({ id: 'preacher-curl', name: 'Preacher Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps'], primaryRegion: 'biceps', equipment: ['preacher bench', 'ez bar', 'plates'], description: 'Supported curl for strict elbow flexion and repeatable setup.', roleTags: ['accessory', 'biceps', 'low fatigue'] }),
  movement({ id: 'machine-preacher-curl', name: 'Machine Preacher Curl', family: 'Curl', aliases: ['Preacher Curl Machine'], pattern: 'isolation', regions: ['biceps'], primaryRegion: 'biceps', equipment: ['preacher curl machine'], description: 'Stable machine curl for direct biceps loading.', roleTags: ['accessory', 'biceps', 'machine', 'low fatigue'] }),
  movement({ id: 'bayesian-curl', name: 'Bayesian Cable Curl', family: 'Curl', aliases: ['Behind-the-Body Cable Curl'], pattern: 'isolation', regions: ['biceps'], primaryRegion: 'biceps', equipment: ['cable station', 'single handle'], description: 'Behind-the-body cable curl for biceps loading at a long muscle length.', roleTags: ['accessory', 'biceps', 'lengthened'] }),
  movement({ id: 'cable-curl', name: 'Cable Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps', 'forearms'], primaryRegion: 'biceps', equipment: ['cable station', 'straight bar attachment'], description: 'Cable elbow flexion with a stable resistance line.', roleTags: ['accessory', 'biceps', 'low fatigue'] }),
  movement({ id: 'reverse-curl', name: 'EZ-Bar Reverse Curl', family: 'Curl', aliases: ['Reverse Curl'], pattern: 'isolation', regions: ['forearms', 'biceps'], primaryRegion: 'forearms', equipment: ['ez bar', 'plates'], description: 'Pronated curl for forearms and elbow flexors.', roleTags: ['accessory', 'forearms', 'biceps'] }),

  // Calves, trunk, and carries
  movement({ id: 'standing-calf-raise', name: 'Standing Calf Raise', family: 'Calf Raise', aliases: ['Machine Calf Raise'], pattern: 'isolation', regions: ['calves'], primaryRegion: 'calves', equipment: ['standing calf raise machine'], description: 'Straight-knee calf raise for direct calf loading.', roleTags: ['accessory', 'calves', 'machine'] }),
  movement({ id: 'seated-calf-raise', name: 'Seated Calf Raise', family: 'Calf Raise', pattern: 'isolation', regions: ['calves'], primaryRegion: 'calves', equipment: ['seated calf raise machine'], description: 'Bent-knee calf raise for direct calf work.', roleTags: ['accessory', 'calves', 'machine'] }),
  movement({ id: 'leg-press-calf-raise', name: 'Leg Press Calf Raise', family: 'Calf Raise', pattern: 'isolation', regions: ['calves'], primaryRegion: 'calves', equipment: ['leg press machine'], description: 'Calf raise performed on a leg press for stable high-repetition loading.', roleTags: ['accessory', 'calves', 'machine'] }),
  movement({ id: 'single-leg-calf-raise', name: 'Single-Leg Calf Raise', family: 'Calf Raise', pattern: 'isolation', regions: ['calves'], primaryRegion: 'calves', equipment: ['dumbbells', 'step'], description: 'Unilateral calf raise for side-to-side calf training.', roleTags: ['accessory', 'calves', 'unilateral'] }),
  movement({ id: 'cable-crunch', name: 'Kneeling Cable Crunch', family: 'Trunk Flexion', aliases: ['Cable Crunch', 'Kneeling Crunch'], pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['cable station', 'rope'], description: 'Loaded trunk flexion for direct abdominal work.', roleTags: ['accessory', 'abs', 'short setup'] }),
  movement({ id: 'hanging-leg-raise', name: 'Hanging Leg Raise', family: 'Trunk Flexion', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['pull-up bar'], description: 'Hanging trunk and hip flexion for abdominal training.', roleTags: ['accessory', 'abs', 'bodyweight'] }),
  movement({ id: 'reverse-crunch', name: 'Reverse Crunch', family: 'Trunk Flexion', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['bodyweight'], description: 'Bodyweight posterior pelvic curl for abdominal work.', roleTags: ['accessory', 'abs', 'bodyweight', 'short setup'] }),
  movement({ id: 'pallof-press', name: 'Pallof Press', family: 'Anti-Rotation', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['cable station', 'single handle'], description: 'Cable anti-rotation press for oblique and trunk control.', roleTags: ['accessory', 'obliques', 'low fatigue'] }),
  movement({ id: 'weighted-plank', name: 'Weighted Plank', family: 'Anti-Extension', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['bodyweight', 'plates'], description: 'Loaded isometric anti-extension work for the trunk.', roleTags: ['accessory', 'abs', 'short setup'] }),
  movement({ id: 'farmers-carry', name: 'Farmer Carry', family: 'Loaded Carry', aliases: ["Farmer's Walk"], pattern: 'carry', regions: ['forearms', 'trunk', 'traps', 'back'], primaryRegion: 'forearms', equipment: ['dumbbells'], description: 'Bilateral loaded carry for grip, trunk, trapezius, and upper-back work.', roleTags: ['accessory', 'grip', 'traps', 'conditioning'] }),
  movement({ id: 'suitcase-carry', name: 'Suitcase Carry', family: 'Loaded Carry', pattern: 'carry', regions: ['trunk', 'forearms'], primaryRegion: 'trunk', equipment: ['dumbbells'], description: 'Unilateral loaded carry for anti-lateral-flexion and grip.', roleTags: ['accessory', 'obliques', 'grip', 'unilateral'] })
]

export const expandedCommercialEquipment = [
  'assisted dip machine', 'assisted pull-up machine', 'back extension bench', 'bands', 'belt squat machine', 'blocks', 'bodyweight', 'box', 'buffalo bar', 'chains',
  'chest press machine', 'decline bench', 'dip station', 'ez bar', 'glute ham developer', 'horizontal leg press machine', 'landmine', 'lateral raise machine',
  'leg extension machine', 'leg press machine', 'lying leg curl machine', 'nordic bench', 'pec deck machine', 'pendulum squat machine', 'plate-loaded chest press',
  'preacher bench', 'preacher curl machine', 'pull-up bar', 'pulldown bar', 'pullover machine', 'push-up handles', 'reverse hyper machine', 'row handle',
  'seal row bench', 'seated calf raise machine', 'shoulder press machine', 'single handle', 'smith machine', 'standing calf raise machine',
  'standing leg curl machine', 'step', 'straight bar attachment', 'swiss bar', 't-bar row machine', 'trap bar', 'v-squat machine'
]
