import type { BodyRegion, Exercise, MovementPattern } from './types'

type CatalogEntry = {
  id: string
  name: string
  family: string
  aliases?: string[]
  pattern: MovementPattern
  regions: BodyRegion[]
  primaryRegion: BodyRegion
  equipment: string[]
  description: string
  roleTags: string[]
}

const movement = (entry: CatalogEntry): Exercise => ({
  ...entry,
  aliases: entry.aliases ?? [],
  favorite: false,
  jointFeeling: 'neutral'
})

/**
 * A second catalog pass covering the less common work an experienced lifter actually reaches for:
 * specialty-bar and machine variations, suspension and bodyweight options that travel, strongman
 * implements, and the small isolation movements a full program eventually needs. Naming is original
 * and descriptive: where a movement is known by a brand, the brand stays in the alias so search finds
 * it while the catalog name still describes the movement.
 */
export const extraExercises: Exercise[] = [
  // Squat pattern, quadriceps, and unilateral lower body
  movement({ id: 'sissy-squat', name: 'Sissy Squat', family: 'Knee Extension', aliases: ['Bodyweight Sissy Squat'], pattern: 'squat', regions: ['quadriceps'], primaryRegion: 'quadriceps', equipment: ['sissy squat bench'], description: 'Knee-dominant squat through a long quadriceps range with the hips held extended.', roleTags: ['hypertrophy', 'quads', 'lengthened position'] }),
  movement({ id: 'cyclist-squat', name: 'Cyclist Squat', family: 'Squat', aliases: ['Heels-Elevated Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates', 'deficit platform'], description: 'Heel-elevated squat that keeps the shin angle forward for a quadriceps bias.', roleTags: ['hypertrophy', 'quads', 'squat'] }),
  movement({ id: 'zercher-squat', name: 'Zercher Squat', family: 'Squat', pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk', 'back'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates'], description: 'Squat carried in the elbow crease, taxing the trunk and upper back alongside the legs.', roleTags: ['strength', 'trunk', 'specialty'] }),
  movement({ id: 'hatfield-squat', name: 'Hatfield Squat', family: 'Machine Squat', aliases: ['Safety Bar Hand-Supported Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['safety squat bar', 'rack', 'plates'], description: 'Safety-bar squat with hands on the rails, letting the legs work past what trunk fatigue allows.', roleTags: ['hypertrophy', 'quads', 'high output'] }),
  movement({ id: 'landmine-squat', name: 'Landmine Squat', family: 'Squat', pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['landmine', 'plates'], description: 'Arced front-loaded squat that is easy to set up and forgiving on the shoulders.', roleTags: ['hypertrophy', 'quads', 'joint friendly'] }),
  movement({ id: 'trap-bar-squat', name: 'Trap Bar Squat', family: 'Squat', aliases: ['High-Handle Trap Bar Squat'], pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['trap bar', 'plates'], description: 'Upright trap-bar squat pattern with a neutral grip and a short learning curve.', roleTags: ['hypertrophy', 'quads', 'beginner friendly'] }),
  movement({ id: 'smith-split-squat', name: 'Smith Machine Split Squat', family: 'Split Squat', pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['smith machine'], description: 'Fixed-path split squat that removes balance from unilateral leg work.', roleTags: ['hypertrophy', 'unilateral', 'machine'] }),
  movement({ id: 'front-rack-lunge', name: 'Front-Rack Lunge', family: 'Lunge', pattern: 'squat', regions: ['quadriceps', 'glutes', 'trunk'], primaryRegion: 'quadriceps', equipment: ['barbell', 'rack', 'plates'], description: 'Front-loaded lunge that keeps the torso upright and the front leg working.', roleTags: ['hypertrophy', 'unilateral', 'trunk'] }),
  movement({ id: 'cossack-squat', name: 'Cossack Squat', family: 'Lateral Squat', pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['bodyweight'], description: 'Deep side-to-side squat that loads one leg while the other extends.', roleTags: ['unilateral', 'range of motion', 'adductors'] }),
  movement({ id: 'curtsy-lunge', name: 'Curtsy Lunge', family: 'Lunge', pattern: 'squat', regions: ['glutes', 'quadriceps'], primaryRegion: 'glutes', equipment: ['dumbbells'], description: 'Crossing lunge that biases the gluteus medius of the front leg.', roleTags: ['hypertrophy', 'glutes', 'unilateral'] }),
  movement({ id: 'deficit-step-down', name: 'Deficit Step-Down', family: 'Step-Up', pattern: 'squat', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['box', 'dumbbells'], description: 'Controlled single-leg lowering from a box for quadriceps and knee control.', roleTags: ['unilateral', 'control', 'hypertrophy'] }),
  movement({ id: 'sled-push', name: 'Sled Push', family: 'Sled', aliases: ['Prowler Push'], pattern: 'carry', regions: ['quadriceps', 'glutes', 'calves'], primaryRegion: 'quadriceps', equipment: ['sled'], description: 'Horizontal pushing work with almost no eccentric, useful when recovery is the limit.', roleTags: ['conditioning', 'low soreness', 'quads'] }),

  // Hinge, hamstrings, and glutes
  movement({ id: 'kettlebell-swing', name: 'Kettlebell Swing', family: 'Ballistic Hinge', pattern: 'hinge', regions: ['glutes', 'hamstrings', 'back'], primaryRegion: 'glutes', equipment: ['kettlebell'], description: 'Ballistic hinge driven by the hips, trained for speed rather than grinding load.', roleTags: ['power', 'conditioning', 'glutes'] }),
  movement({ id: 'seated-good-morning', name: 'Seated Good Morning', family: 'Good Morning', pattern: 'hinge', regions: ['hamstrings', 'back', 'trunk'], primaryRegion: 'back', equipment: ['barbell', 'rack', 'bench', 'plates'], description: 'Seated hinge that removes the hamstring stretch and loads the spinal erectors directly.', roleTags: ['strength', 'erectors', 'weak point'] }),
  movement({ id: 'jefferson-curl', name: 'Jefferson Curl', family: 'Loaded Flexion', pattern: 'hinge', regions: ['hamstrings', 'back'], primaryRegion: 'hamstrings', equipment: ['dumbbells'], description: 'Slow segmental spinal flexion under light load, trained for range rather than strength.', roleTags: ['range of motion', 'light load', 'technique'] }),
  movement({ id: 'slider-leg-curl', name: 'Slider Leg Curl', family: 'Leg Curl', aliases: ['Valslide Curl', 'Towel Curl'], pattern: 'isolation', regions: ['hamstrings', 'glutes'], primaryRegion: 'hamstrings', equipment: ['sliders', 'bodyweight'], description: 'Supine knee flexion against friction, available anywhere with a smooth floor.', roleTags: ['hamstrings', 'travel friendly', 'bodyweight'] }),
  movement({ id: 'stability-ball-curl', name: 'Stability Ball Leg Curl', family: 'Leg Curl', pattern: 'isolation', regions: ['hamstrings', 'glutes'], primaryRegion: 'hamstrings', equipment: ['stability ball', 'bodyweight'], description: 'Supine knee flexion with the heels on a ball, adding a hip-extension demand.', roleTags: ['hamstrings', 'bodyweight', 'accessory'] }),
  movement({ id: 'razor-curl', name: 'Razor Curl', family: 'Leg Curl', pattern: 'isolation', regions: ['hamstrings', 'glutes'], primaryRegion: 'hamstrings', equipment: ['glute ham developer'], description: 'Hip-flexed knee curl on a developer pad that keeps tension high through the range.', roleTags: ['hamstrings', 'hypertrophy'] }),
  movement({ id: 'cable-kickback', name: 'Cable Glute Kickback', family: 'Hip Extension', pattern: 'isolation', regions: ['glutes'], primaryRegion: 'glutes', equipment: ['cable station', 'single handle'], description: 'Single-leg hip extension against a cable with a short, repeatable setup.', roleTags: ['glutes', 'isolation', 'unilateral'] }),
  movement({ id: 'frog-pump', name: 'Frog Pump', family: 'Hip Extension', pattern: 'hinge', regions: ['glutes'], primaryRegion: 'glutes', equipment: ['plates', 'bodyweight'], description: 'Short-range hip extension with the soles together, biasing the gluteals over the hamstrings.', roleTags: ['glutes', 'high repetition', 'accessory'] }),
  movement({ id: 'glute-drive-machine', name: 'Glute Drive Machine', family: 'Hip Extension', pattern: 'hinge', regions: ['glutes', 'hamstrings'], primaryRegion: 'glutes', equipment: ['glute drive machine'], description: 'Seated machine hip extension with a fixed path and easy loading.', roleTags: ['glutes', 'machine', 'hypertrophy'] }),
  movement({ id: 'seated-hip-abduction', name: 'Seated Hip Abduction', family: 'Hip Abduction', pattern: 'isolation', regions: ['glutes'], primaryRegion: 'glutes', equipment: ['hip abduction machine'], description: 'Seated machine abduction for the gluteus medius and minimus.', roleTags: ['glutes', 'machine', 'isolation'] }),
  movement({ id: 'cable-hip-abduction', name: 'Standing Cable Abduction', family: 'Hip Abduction', pattern: 'isolation', regions: ['glutes'], primaryRegion: 'glutes', equipment: ['cable station', 'single handle'], description: 'Standing single-leg abduction against a cable, loaded in a lengthened position.', roleTags: ['glutes', 'unilateral', 'isolation'] }),
  movement({ id: 'hip-adduction-machine', name: 'Hip Adduction Machine', family: 'Hip Adduction', pattern: 'isolation', regions: ['quadriceps', 'glutes'], primaryRegion: 'quadriceps', equipment: ['hip adduction machine'], description: 'Seated machine adduction for the groin and inner thigh.', roleTags: ['adductors', 'machine', 'isolation'] }),
  movement({ id: 'axle-deadlift', name: 'Axle Deadlift', family: 'Deadlift', aliases: ['Fat Bar Deadlift'], pattern: 'hinge', regions: ['back', 'glutes', 'hamstrings', 'forearms'], primaryRegion: 'back', equipment: ['axle bar', 'plates'], description: 'Thick-bar pull where grip, not the hips, usually sets the ceiling.', roleTags: ['strongman', 'grip', 'strength'] }),
  movement({ id: 'suitcase-deadlift', name: 'Suitcase Deadlift', family: 'Deadlift', pattern: 'hinge', regions: ['trunk', 'glutes', 'back'], primaryRegion: 'trunk', equipment: ['barbell', 'plates'], description: 'Offset single-side pull that asks the trunk to resist side bending.', roleTags: ['trunk', 'anti-lateral flexion', 'unilateral'] }),

  // Chest and pressing
  movement({ id: 'weighted-dip', name: 'Weighted Dip', family: 'Dip', pattern: 'vertical-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['dip station', 'plates'], description: 'Loaded parallel-bar dip for chest and triceps strength in a lengthened position.', roleTags: ['strength', 'hypertrophy', 'chest'] }),
  movement({ id: 'ring-dip', name: 'Ring Dip', family: 'Dip', pattern: 'vertical-push', regions: ['chest', 'triceps', 'shoulders'], primaryRegion: 'chest', equipment: ['rings'], description: 'Unstable dip on rings, demanding shoulder control before load.', roleTags: ['control', 'bodyweight', 'chest'] }),
  movement({ id: 'guillotine-press', name: 'Guillotine Press', family: 'Bench Press', aliases: ['Neck Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps'], primaryRegion: 'chest', equipment: ['barbell', 'bench', 'rack', 'plates'], description: 'High-to-the-collarbone press path that biases the upper chest. Load conservatively.', roleTags: ['hypertrophy', 'upper chest', 'advanced'] }),
  movement({ id: 'squeeze-press', name: 'Squeeze Press', family: 'Dumbbell Press', aliases: ['Crush Grip Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps'], primaryRegion: 'chest', equipment: ['dumbbells', 'bench'], description: 'Dumbbells pressed together throughout, adding adduction to the press.', roleTags: ['hypertrophy', 'chest', 'joint friendly'] }),
  movement({ id: 'hex-press', name: 'Hex Press', family: 'Dumbbell Press', pattern: 'horizontal-push', regions: ['chest', 'triceps'], primaryRegion: 'chest', equipment: ['dumbbells', 'bench'], description: 'Neutral-grip press with the dumbbells touching, easy on the front of the shoulder.', roleTags: ['joint friendly', 'chest', 'hypertrophy'] }),
  movement({ id: 'reverse-grip-bench', name: 'Reverse-Grip Bench Press', family: 'Bench Press', aliases: ['Supinated Bench Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps'], primaryRegion: 'chest', equipment: ['barbell', 'bench', 'rack', 'plates'], description: 'Supinated press that shifts work toward the upper chest and triceps. Use a spotter.', roleTags: ['upper chest', 'triceps', 'advanced'] }),
  movement({ id: 'incline-smith-press', name: 'Incline Smith Press', family: 'Incline Press', pattern: 'horizontal-push', regions: ['chest', 'shoulders', 'triceps'], primaryRegion: 'chest', equipment: ['smith machine', 'adjustable bench'], description: 'Fixed-path incline press for repeatable upper-chest loading without a spotter.', roleTags: ['hypertrophy', 'upper chest', 'machine'] }),
  movement({ id: 'high-to-low-crossover', name: 'High-to-Low Cable Crossover', family: 'Chest Fly', pattern: 'isolation', regions: ['chest'], primaryRegion: 'chest', equipment: ['cable station', 'single handle'], description: 'Downward cable adduction that biases the lower and mid chest.', roleTags: ['chest', 'isolation', 'peak contraction'] }),
  movement({ id: 'standing-landmine-press', name: 'Standing Landmine Press', family: 'Landmine Press', pattern: 'vertical-push', regions: ['shoulders', 'chest', 'triceps'], primaryRegion: 'shoulders', equipment: ['landmine', 'plates'], description: 'Angled standing press that is friendlier than vertical pressing for many shoulders.', roleTags: ['joint friendly', 'shoulders', 'accessory'] }),
  movement({ id: 'suspension-chest-press', name: 'Suspension Trainer Chest Press', family: 'Suspension Press', aliases: ['TRX Chest Press'], pattern: 'horizontal-push', regions: ['chest', 'triceps', 'trunk'], primaryRegion: 'chest', equipment: ['suspension trainer'], description: 'Bodyweight press on straps where foot position sets the load.', roleTags: ['travel friendly', 'bodyweight', 'chest'] }),
  movement({ id: 'suspension-fly', name: 'Suspension Trainer Fly', family: 'Chest Fly', aliases: ['TRX Fly'], pattern: 'isolation', regions: ['chest', 'trunk'], primaryRegion: 'chest', equipment: ['suspension trainer'], description: 'Bodyweight chest adduction on straps, scaled by how far you lean in.', roleTags: ['travel friendly', 'chest', 'bodyweight'] }),

  // Back and pulling
  movement({ id: 'dead-stop-row', name: 'Dead-Stop Row', family: 'Row', aliases: ['Dead Stop Barbell Row'], pattern: 'horizontal-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['barbell', 'plates', 'rack'], description: 'Row reset on the floor or pins each repetition, removing bounce and stretch reflex.', roleTags: ['strength', 'upper back', 'strict'] }),
  movement({ id: 'kroc-row', name: 'Kroc Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps', 'forearms'], primaryRegion: 'back', equipment: ['dumbbells', 'bench'], description: 'Heavy high-repetition single-arm row with permitted body english and a hard grip demand.', roleTags: ['strength', 'grip', 'high repetition'] }),
  movement({ id: 'helms-row', name: 'Helms Row', family: 'Row', aliases: ['Chest-Supported Incline Row'], pattern: 'horizontal-pull', regions: ['back', 'shoulders', 'biceps'], primaryRegion: 'back', equipment: ['dumbbells', 'adjustable bench'], description: 'Strict incline-supported row with a high elbow path for the upper back and rear delts.', roleTags: ['upper back', 'rear delts', 'strict'] }),
  movement({ id: 'gorilla-row', name: 'Gorilla Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['kettlebell'], description: 'Alternating bent-over row from the floor with the free hand braced on the other bell.', roleTags: ['upper back', 'unilateral', 'accessory'] }),
  movement({ id: 'inverted-row', name: 'Inverted Row', family: 'Row', aliases: ['Bodyweight Row'], pattern: 'horizontal-pull', regions: ['back', 'biceps', 'trunk'], primaryRegion: 'back', equipment: ['barbell', 'rack', 'bodyweight'], description: 'Horizontal bodyweight pull scaled by body angle, useful anywhere with a bar.', roleTags: ['bodyweight', 'upper back', 'beginner friendly'] }),
  movement({ id: 'suspension-row', name: 'Suspension Trainer Row', family: 'Row', aliases: ['TRX Row'], pattern: 'horizontal-pull', regions: ['back', 'biceps', 'trunk'], primaryRegion: 'back', equipment: ['suspension trainer'], description: 'Strap row with load set by foot placement, the most portable back movement here.', roleTags: ['travel friendly', 'bodyweight', 'upper back'] }),
  movement({ id: 'landmine-row', name: 'Landmine Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['landmine', 'plates', 'row handle'], description: 'Two-handed row on a landmine with a fixed arc and an easy loading jump.', roleTags: ['upper back', 'hypertrophy'] }),
  movement({ id: 'seated-high-row', name: 'Seated Machine High Row', family: 'Row', pattern: 'horizontal-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['row machine'], description: 'High-elbow machine row that emphasizes the upper back over the lats.', roleTags: ['upper back', 'machine', 'hypertrophy'] }),
  movement({ id: 'kneeling-pulldown', name: 'Kneeling Cable Pulldown', family: 'Vertical Pull', pattern: 'vertical-pull', regions: ['back', 'biceps', 'trunk'], primaryRegion: 'back', equipment: ['cable station', 'pulldown bar'], description: 'Tall-kneeling pulldown that removes the seat and keeps the trunk honest.', roleTags: ['lats', 'trunk', 'accessory'] }),
  movement({ id: 'rack-chin', name: 'Rack Chin', family: 'Vertical Pull', aliases: ['Feet-Supported Chin'], pattern: 'vertical-pull', regions: ['back', 'biceps'], primaryRegion: 'back', equipment: ['rack', 'box', 'bodyweight'], description: 'Chin variation with the feet supported so the load can be scaled below bodyweight.', roleTags: ['lats', 'scalable', 'bodyweight'] }),
  movement({ id: 'suspension-face-pull', name: 'Suspension Trainer Face Pull', family: 'Rear Delt Pull', aliases: ['TRX Face Pull'], pattern: 'horizontal-pull', regions: ['shoulders', 'back'], primaryRegion: 'shoulders', equipment: ['suspension trainer'], description: 'Strap face pull for rear delts and upper back with no machine required.', roleTags: ['rear delts', 'travel friendly', 'shoulder health'] }),

  // Shoulders
  movement({ id: 'z-press', name: 'Z Press', family: 'Overhead Press', aliases: ['Seated Floor Press Overhead'], pattern: 'vertical-push', regions: ['shoulders', 'triceps', 'trunk'], primaryRegion: 'shoulders', equipment: ['barbell', 'rack', 'plates'], description: 'Overhead press seated on the floor with legs straight, removing every leg contribution.', roleTags: ['strict', 'trunk', 'shoulders'] }),
  movement({ id: 'behind-neck-press', name: 'Behind-the-Neck Press', family: 'Overhead Press', pattern: 'vertical-push', regions: ['shoulders', 'triceps'], primaryRegion: 'shoulders', equipment: ['barbell', 'rack', 'plates'], description: 'Press from behind the neck for lateral-delt bias. Needs shoulder range and light progression.', roleTags: ['advanced', 'lateral delts', 'range of motion'] }),
  movement({ id: 'bradford-press', name: 'Bradford Press', family: 'Overhead Press', pattern: 'vertical-push', regions: ['shoulders', 'triceps'], primaryRegion: 'shoulders', equipment: ['barbell', 'rack', 'plates'], description: 'Alternating front-to-back press kept in the mid range for continuous deltoid tension.', roleTags: ['hypertrophy', 'shoulders', 'continuous tension'] }),
  movement({ id: 'viking-press', name: 'Viking Press', family: 'Overhead Press', pattern: 'vertical-push', regions: ['shoulders', 'triceps', 'trunk'], primaryRegion: 'shoulders', equipment: ['landmine', 'plates'], description: 'Neutral-grip machine or landmine press with an arced path, common in strongman.', roleTags: ['strongman', 'shoulders', 'joint friendly'] }),
  movement({ id: 'log-press', name: 'Log Press', family: 'Overhead Press', pattern: 'vertical-push', regions: ['shoulders', 'triceps', 'trunk'], primaryRegion: 'shoulders', equipment: ['log bar', 'plates'], description: 'Thick neutral-grip overhead press from the clean position, a strongman staple.', roleTags: ['strongman', 'power', 'shoulders'] }),
  movement({ id: 'powell-raise', name: 'Powell Raise', family: 'Rear Delt Fly', pattern: 'isolation', regions: ['shoulders', 'back'], primaryRegion: 'shoulders', equipment: ['dumbbells', 'adjustable bench'], description: 'Side-lying raise with a long arm path for the posterior deltoid.', roleTags: ['rear delts', 'isolation', 'lengthened position'] }),
  movement({ id: 'cuban-rotation', name: 'Cuban Rotation', family: 'Shoulder Health', aliases: ['Cuban Press'], pattern: 'isolation', regions: ['shoulders'], primaryRegion: 'shoulders', equipment: ['dumbbells'], description: 'External rotation drilled under light load for shoulder tolerance, never for load records.', roleTags: ['shoulder health', 'light load', 'warmup alternative'] }),
  movement({ id: 'cable-y-raise', name: 'Cable Y-Raise', family: 'Shoulder Raise', pattern: 'isolation', regions: ['shoulders', 'back'], primaryRegion: 'shoulders', equipment: ['cable station', 'single handle'], description: 'Overhead-angled raise that trains the lower traps with the deltoid.', roleTags: ['shoulder health', 'lower traps', 'isolation'] }),
  movement({ id: 'prone-trap-raise', name: 'Prone Trap Raise', family: 'Shoulder Raise', aliases: ['Prone Y Raise'], pattern: 'isolation', regions: ['shoulders', 'back'], primaryRegion: 'back', equipment: ['dumbbells', 'adjustable bench'], description: 'Chest-supported overhead raise for the lower and mid trapezius.', roleTags: ['upper back', 'shoulder health', 'light load'] }),
  movement({ id: 'front-plate-raise', name: 'Front Plate Raise', family: 'Shoulder Raise', pattern: 'isolation', regions: ['shoulders'], primaryRegion: 'shoulders', equipment: ['plates'], description: 'Anterior deltoid raise held on a plate, simple to scale and easy to standardize.', roleTags: ['front delts', 'isolation', 'accessory'] }),
  movement({ id: 'rear-delt-row', name: 'Rear-Delt Row', family: 'Rear Delt Pull', aliases: ['High-Elbow Rear Delt Row'], pattern: 'horizontal-pull', regions: ['shoulders', 'back'], primaryRegion: 'shoulders', equipment: ['dumbbells', 'adjustable bench'], description: 'High-elbow row taken to the chest line for posterior deltoids rather than lats.', roleTags: ['rear delts', 'upper back', 'hypertrophy'] }),

  // Arms
  movement({ id: 'spider-curl', name: 'Spider Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps'], primaryRegion: 'biceps', equipment: ['adjustable bench', 'dumbbells'], description: 'Prone incline curl with the arms hanging vertical, hardest at the top.', roleTags: ['biceps', 'peak contraction', 'isolation'] }),
  movement({ id: 'concentration-curl', name: 'Concentration Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps'], primaryRegion: 'biceps', equipment: ['dumbbells', 'bench'], description: 'Braced single-arm curl that makes cheating obvious and keeps the elbow fixed.', roleTags: ['biceps', 'strict', 'unilateral'] }),
  movement({ id: 'zottman-curl', name: 'Zottman Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps', 'forearms'], primaryRegion: 'biceps', equipment: ['dumbbells'], description: 'Supinated lift and pronated lower, training the elbow flexors and forearms in one set.', roleTags: ['biceps', 'forearms', 'efficient'] }),
  movement({ id: 'drag-curl', name: 'Drag Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps'], primaryRegion: 'biceps', equipment: ['barbell', 'plates'], description: 'Curl with the bar dragged up the torso and the elbows travelling back.', roleTags: ['biceps', 'short head', 'isolation'] }),
  movement({ id: 'preacher-hammer-curl', name: 'Preacher Hammer Curl', family: 'Curl', pattern: 'isolation', regions: ['biceps', 'forearms'], primaryRegion: 'biceps', equipment: ['preacher bench', 'dumbbells'], description: 'Neutral-grip curl braced on a preacher pad for the brachialis and brachioradialis.', roleTags: ['brachialis', 'forearms', 'strict'] }),
  movement({ id: 'suspension-curl', name: 'Suspension Trainer Curl', family: 'Curl', aliases: ['TRX Curl'], pattern: 'isolation', regions: ['biceps', 'trunk'], primaryRegion: 'biceps', equipment: ['suspension trainer'], description: 'Bodyweight elbow flexion on straps, scaled by how far the feet walk forward.', roleTags: ['travel friendly', 'biceps', 'bodyweight'] }),
  movement({ id: 'reverse-grip-pushdown', name: 'Reverse-Grip Pushdown', family: 'Triceps Extension', pattern: 'isolation', regions: ['triceps'], primaryRegion: 'triceps', equipment: ['cable station', 'straight bar attachment'], description: 'Supinated pushdown that biases the medial head and spares the elbow.', roleTags: ['triceps', 'joint friendly', 'isolation'] }),
  movement({ id: 'katana-extension', name: 'Katana Extension', family: 'Triceps Extension', aliases: ['Cable Overhead Katana'], pattern: 'isolation', regions: ['triceps'], primaryRegion: 'triceps', equipment: ['cable station', 'single handle'], description: 'Single-arm cross-body overhead extension that loads the long head at length.', roleTags: ['triceps', 'long head', 'lengthened position'] }),
  movement({ id: 'bench-dip', name: 'Bench Dip', family: 'Dip', pattern: 'isolation', regions: ['triceps', 'chest'], primaryRegion: 'triceps', equipment: ['bench', 'bodyweight'], description: 'Seated-support triceps dip, scalable by foot position and easy to set up anywhere.', roleTags: ['triceps', 'bodyweight', 'travel friendly'] }),
  movement({ id: 'suspension-triceps-press', name: 'Suspension Trainer Triceps Press', family: 'Triceps Extension', aliases: ['TRX Triceps Press'], pattern: 'isolation', regions: ['triceps', 'trunk'], primaryRegion: 'triceps', equipment: ['suspension trainer'], description: 'Overhead strap extension where body angle sets the load.', roleTags: ['triceps', 'travel friendly', 'bodyweight'] }),
  movement({ id: 'wrist-curl', name: 'Wrist Curl', family: 'Forearm', pattern: 'isolation', regions: ['forearms'], primaryRegion: 'forearms', equipment: ['dumbbells', 'bench'], description: 'Direct wrist flexion for the forearm flexors and grip endurance.', roleTags: ['forearms', 'grip', 'isolation'] }),
  movement({ id: 'wrist-extension', name: 'Wrist Extension', family: 'Forearm', aliases: ['Reverse Wrist Raise'], pattern: 'isolation', regions: ['forearms'], primaryRegion: 'forearms', equipment: ['dumbbells', 'bench'], description: 'Direct wrist extension, commonly trained for elbow tolerance in heavy pullers.', roleTags: ['forearms', 'elbow health', 'isolation'] }),
  movement({ id: 'wrist-roller', name: 'Wrist Roller', family: 'Forearm', pattern: 'isolation', regions: ['forearms'], primaryRegion: 'forearms', equipment: ['wrist roller', 'plates'], description: 'Rolling a hanging load up and down for continuous forearm work.', roleTags: ['forearms', 'grip', 'endurance'] }),
  movement({ id: 'plate-pinch', name: 'Plate Pinch Hold', family: 'Grip', pattern: 'carry', regions: ['forearms'], primaryRegion: 'forearms', equipment: ['plates'], description: 'Pinch grip hold on smooth plates, trained for time rather than repetitions.', roleTags: ['grip', 'hold', 'strongman'] }),

  // Calves, trunk, and carries
  movement({ id: 'donkey-calf-raise', name: 'Donkey Calf Raise', family: 'Calf Raise', pattern: 'isolation', regions: ['calves'], primaryRegion: 'calves', equipment: ['standing calf raise machine'], description: 'Hip-flexed calf raise that keeps the knee straight and the gastrocnemius long.', roleTags: ['calves', 'lengthened position', 'hypertrophy'] }),
  movement({ id: 'smith-calf-raise', name: 'Smith Machine Calf Raise', family: 'Calf Raise', pattern: 'isolation', regions: ['calves'], primaryRegion: 'calves', equipment: ['smith machine', 'box'], description: 'Fixed-path standing calf raise loaded on a smith bar over a step.', roleTags: ['calves', 'machine', 'hypertrophy'] }),
  movement({ id: 'tibialis-raise', name: 'Tibialis Raise', family: 'Shin', aliases: ['Toe Raise'], pattern: 'isolation', regions: ['calves'], primaryRegion: 'calves', equipment: ['bodyweight', 'plates'], description: 'Dorsiflexion work for the front of the shin, usually trained for knee and ankle tolerance.', roleTags: ['shins', 'joint health', 'isolation'] }),
  movement({ id: 'copenhagen-plank', name: 'Copenhagen Plank', family: 'Anti-Lateral Flexion', pattern: 'carry', regions: ['trunk', 'quadriceps'], primaryRegion: 'trunk', equipment: ['bench', 'bodyweight'], description: 'Side plank with the top leg supported, loading the adductors and lateral trunk.', roleTags: ['adductors', 'trunk', 'groin health'] }),
  movement({ id: 'side-plank', name: 'Side Plank', family: 'Anti-Lateral Flexion', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['bodyweight'], description: 'Timed lateral trunk hold, progressed by load or lever rather than repetitions.', roleTags: ['trunk', 'obliques', 'bodyweight'] }),
  movement({ id: 'dead-bug', name: 'Dead Bug', family: 'Anti-Extension', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['bodyweight'], description: 'Supine limb lowering while the low back stays flat, trained for control not fatigue.', roleTags: ['trunk', 'control', 'bodyweight'] }),
  movement({ id: 'hollow-body-hold', name: 'Hollow Body Hold', family: 'Anti-Extension', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['bodyweight'], description: 'Timed supine hold with the ribs down, a strict progression before heavy flexion work.', roleTags: ['trunk', 'hold', 'bodyweight'] }),
  movement({ id: 'cable-woodchop', name: 'Cable Woodchop', family: 'Rotation', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['cable station', 'single handle'], description: 'Diagonal cable rotation trained for controlled speed rather than maximum load.', roleTags: ['obliques', 'rotation', 'trunk'] }),
  movement({ id: 'landmine-rotation', name: 'Landmine Rotation', family: 'Rotation', pattern: 'carry', regions: ['trunk', 'shoulders'], primaryRegion: 'trunk', equipment: ['landmine', 'plates'], description: 'Arced rotational work with the bar held at arm length.', roleTags: ['obliques', 'rotation', 'trunk'] }),
  movement({ id: 'hanging-knee-raise', name: 'Hanging Knee Raise', family: 'Trunk Flexion', pattern: 'carry', regions: ['trunk'], primaryRegion: 'trunk', equipment: ['pull-up bar', 'bodyweight'], description: 'Hanging hip flexion with bent knees, the scalable step below a straight-leg raise.', roleTags: ['trunk', 'bodyweight', 'scalable'] }),
  movement({ id: 'l-sit', name: 'L-Sit Hold', family: 'Trunk Flexion', pattern: 'carry', regions: ['trunk', 'quadriceps'], primaryRegion: 'trunk', equipment: ['dip station', 'bodyweight'], description: 'Supported hold with the legs held horizontal, trained for time.', roleTags: ['trunk', 'hold', 'bodyweight'] }),
  movement({ id: 'zercher-carry', name: 'Zercher Carry', family: 'Loaded Carry', pattern: 'carry', regions: ['trunk', 'back', 'forearms'], primaryRegion: 'trunk', equipment: ['barbell', 'plates'], description: 'Carry with the bar in the elbows, loading the trunk and upper back on every step.', roleTags: ['trunk', 'upper back', 'strongman'] }),
  movement({ id: 'sandbag-carry', name: 'Sandbag Carry', family: 'Loaded Carry', aliases: ['Bear Hug Carry'], pattern: 'carry', regions: ['trunk', 'back', 'glutes'], primaryRegion: 'trunk', equipment: ['sandbag'], description: 'Awkward bear-hug carry where the load shifts and the trunk keeps resisting it.', roleTags: ['strongman', 'trunk', 'conditioning'] }),
  movement({ id: 'yoke-walk', name: 'Yoke Walk', family: 'Loaded Carry', pattern: 'carry', regions: ['trunk', 'back', 'quadriceps'], primaryRegion: 'trunk', equipment: ['yoke'], description: 'Heavy axial carry under a yoke, progressed by distance as much as by load.', roleTags: ['strongman', 'axial load', 'trunk'] }),
  movement({ id: 'sled-drag', name: 'Backward Sled Drag', family: 'Sled', pattern: 'carry', regions: ['quadriceps', 'calves'], primaryRegion: 'quadriceps', equipment: ['sled'], description: 'Backward dragging work with no eccentric, often used around sore or cranky knees.', roleTags: ['knee health', 'low soreness', 'conditioning'] })
]

/** Equipment the additions above introduce, added to the shipped commercial-gym profile. */
export const extraCommercialEquipment = [
  'axle bar', 'glute drive machine', 'hip abduction machine', 'hip adduction machine', 'kettlebell', 'log bar', 'rings', 'sandbag',
  'sissy squat bench', 'sled', 'sliders', 'stability ball', 'suspension trainer', 'wrist roller', 'yoke'
]

/** Portable additions, so a home or travel profile can execute the bodyweight and strap work. */
export const extraPortableEquipment = ['bands', 'kettlebell', 'sliders', 'stability ball', 'suspension trainer']
