import { expect, test } from '@playwright/test'

async function enterRecommendedProfile(page: import('@playwright/test').Page) {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: /Quick Start/ }).click()
  await expect(page.getByRole('heading', { name: 'Your next useful win.' })).toBeVisible()
}

test('validates an athlete-controlled PR without changing the prescription', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Why this session?' }).click()
  await expect(page.getByRole('dialog')).toContainText('Powerbuilding route')
  if (testInfo.project.name === 'mobile-chromium') await page.getByRole('dialog').screenshot({ path: 'output/playwright/route-session-explanation-mobile.png' })
  await page.getByRole('button', { name: 'Understood' }).click()
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await expect(page.getByRole('heading', { name: 'Bench Powerbuilding Session' })).toBeVisible()
  await expect(page.getByText('Productive hold:', { exact: false }).first()).toBeVisible()
  await expect(page.locator('.exercise-card--primary')).toContainText('Route-specific warm-up')
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.exercise-card--primary').screenshot({ path: 'output/playwright/route-generated-workout-mobile.png' })

  const firstLoad = page.getByLabel('Set 1 load').first()
  await firstLoad.fill('185')
  await expect(page.getByText('Productive hold:', { exact: false }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await expect(page.getByText('Provisional until the workout is finished and saved.').first()).toBeVisible()

  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: /Full.*10 questions/ }).click()
  await page.getByRole('button', { name: 'How consistent was your technique?: 4' }).click()
  await page.getByRole('button', { name: 'Did any movement create joint pain or irritation?: 0' }).click()
  await page.getByRole('button', { name: 'Save feedback & finish' }).click()
  await expect(page.getByRole('heading', { name: 'PRs and micro wins' })).toBeVisible()
  await expect(page.getByText('Strength PR').first()).toBeVisible()
  await expect(page.getByText('185 heaviest completed load', { exact: false }).first()).toBeVisible()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/progress-achievements-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('keeps achievement controls optional and mobile layouts contained', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'You', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Achievement controls' })).toBeVisible()
  const quietMode = page.getByRole('checkbox', { name: 'Quiet mode' })
  await quietMode.check()
  await page.reload()
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByRole('checkbox', { name: 'Quiet mode' })).toBeChecked()

  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/gamification-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('explains a protected-primary substitution and preserves its outcome evidence', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await page.getByRole('button', { name: 'Change' }).first().click()
  await page.getByLabel('Substitution reason').selectOption('equipment')
  await page.getByRole('button', { name: /Coffin Press/ }).click()
  await expect(page.getByRole('alert')).toContainText('Confirm the protected-primary tradeoff')
  await page.getByRole('checkbox', { name: 'Confirm primary-anchor change' }).check()
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/substitution-picker-mobile.png', fullPage: true })
  await page.getByRole('button', { name: /Coffin Press/ }).click()
  await expect(page.getByText('Baseline calibration', { exact: true })).toBeVisible()
  await expect(page.getByText("The replaced movement's load was not copied", { exact: false })).toBeVisible()
  await page.getByLabel('Set 1 load').first().fill('40')
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: 'Finish workout without survey' }).click()
  await page.getByRole('button', { name: 'Library' }).click()
  await expect(page.getByRole('heading', { name: 'Exercise substitution ledger' })).toBeVisible()
  await expect(page.getByText('Competition Bench Press', { exact: false }).last()).toBeVisible()
  await expect(page.getByText('Coffin Press', { exact: false }).last()).toBeVisible()
  await expect(page.getByText('1 completed source set', { exact: false })).toBeVisible()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/substitution-ledger-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('honors minimal and off survey preferences without inventing answers', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'You' }).click()
  await page.getByLabel('Pre-session check-in mode').selectOption('minimal')
  await page.getByLabel('Post-session feedback mode').selectOption('off')
  await page.getByRole('button', { name: 'Today' }).click()
  await page.getByRole('button', { name: 'Minimal check-in & start' }).click()
  await expect(page.getByRole('heading', { name: 'Minimal readiness check' })).toBeVisible()
  await expect(page.locator('.survey-question')).toHaveCount(3)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/minimal-readiness-mobile.png', fullPage: true })
  await page.locator('.survey-question').first().getByRole('button', { name: 'Not sure' }).click()
  await page.getByRole('button', { name: 'Any soreness, aches, or pain affecting movement?: 0' }).click()
  await page.getByLabel('How many minutes do you actually have?').fill('45')
  await page.getByRole('button', { name: 'Use my check-in' }).click()
  await expect(page.getByText('low survey confidence')).toBeVisible()
  await expect(page.getByText('45 minute version')).toBeVisible()
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await expect(page.getByRole('heading', { name: 'PRs and micro wins' })).toBeVisible()
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByLabel('Post-session feedback mode')).toHaveValue('off')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  const surveys = persisted?.state?.surveys ?? []
  expect(surveys.at(-2)).toMatchObject({ type: 'pre', mode: 'minimal', answeredCount: 2, unknownCount: 1, confidence: 'low' })
  expect(surveys.at(-1)).toMatchObject({ type: 'post', mode: 'off', skipped: true, answeredCount: 0, unknownCount: 0, confidence: 'low' })
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/survey-preferences-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('defers optional feedback without blocking training and replays quality evidence later', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await page.getByLabel('Set 1 load').first().fill('185')
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: /Minimal.*3 essential questions/ }).click()
  await page.getByRole('button', { name: 'Remind me later' }).click()
  await expect(page.getByRole('heading', { name: 'PRs and micro wins' })).toBeVisible()
  await expect(page.getByText('Unverified number best').first()).toBeVisible()

  await page.getByRole('button', { name: 'Today' }).click()
  await expect(page.getByLabel('Optional session feedback')).toBeVisible()
  await expect(page.getByRole('button', { name: /check-in & start|Start workout now/ })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/deferred-feedback-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Add feedback' }).click()
  await expect(page.getByRole('heading', { name: 'Optional Minimal session feedback' })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/deferred-feedback-form-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'How difficult was the session overall?: 7' }).click()
  await page.getByRole('button', { name: 'How consistent was your technique?: 4' }).click()
  await page.getByRole('button', { name: 'Did any movement create joint pain or irritation?: 0' }).click()
  await page.getByRole('button', { name: 'Save feedback' }).click()
  await expect(page.getByLabel('Optional session feedback')).toHaveCount(0)
  await page.getByRole('button', { name: 'Progress' }).click()
  await expect(page.getByText('Strength PR').first()).toBeVisible()
  await expect(page.getByText('185 heaviest completed load', { exact: false }).first()).toBeVisible()

  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted?.version).toBe(17)
  expect(persisted?.state?.deferredFeedback?.at(-1)).toMatchObject({ mode: 'minimal', status: 'completed' })
  expect(persisted?.state?.deferredFeedback?.at(-1)?.surveyId).toBeTruthy()
  expect(persisted?.state?.history?.filter((workSet: { sessionId: string }) => workSet.sessionId === persisted.state.deferredFeedback.at(-1).sessionId).every((workSet: { qualityConfirmed?: boolean }) => workSet.qualityConfirmed === true)).toBe(true)
  expect(persisted?.state?.placementVerifications?.at(-1)?.sessionEvidence).toMatchObject({ difficulty: 7, technique: 4, pain: 0, timeFit: null, postSurveySkipped: false })
  expect(persisted?.state?.placementVerifications?.at(-1)?.firstSet?.sourceSetId).toBeTruthy()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('shows calendar-quarter progress, exact movement mix, and honest priority attention', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Progress' }).click()
  await page.getByRole('button', { name: 'Qtr' }).click()
  await expect(page.getByRole('heading', { name: 'Monthly volume load' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'What filled this window' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Goal-relative completed evidence' })).toBeVisible()
  await expect(page.getByText('share of selected-period volume load, not share of hypertrophy stimulus or enjoyment', { exact: false })).toBeVisible()
  await expect(page.getByText('neither treats one below-plan window as neglect or catch-up debt', { exact: false })).toBeVisible()
  await expect(page.locator('.progress-range button')).toHaveCount(7)
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/quarter-movement-mix-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('shows transparent individual muscle dose with overlap-safe area rollups and source drilldown', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Progress' }).click()
  await page.getByRole('button', { name: 'All time' }).click()
  await expect(page.getByRole('heading', { name: 'Direct work and secondary set credit' })).toBeVisible()
  await expect(page.getByText('Muscle totals are non-additive across rows', { exact: false })).toBeVisible()
  await expect(page.getByLabel('Overlap-safe area dose')).toContainText('Whole body')
  await page.getByRole('button', { name: 'arms', exact: true }).click()
  await expect(page.getByLabel('arms individual muscle dose')).toBeVisible()
  const triceps = page.getByLabel('arms individual muscle dose').getByRole('button', { name: /Triceps/ })
  await triceps.click()
  await expect(page.getByText('Dose provenance')).toBeVisible()
  const sourceIdentifiers = page.locator('.muscle-dose-exercises summary').first()
  await expect(sourceIdentifiers).toContainText('source set identifiers')
  await sourceIdentifiers.click()
  await expect(page.locator('.muscle-dose-exercises code').first()).not.toBeEmpty()
  await expect(page.getByRole('heading', { name: 'Intended set credit versus linked completion' })).toBeVisible()
  await expect(page.getByLabel('arms planned muscle dose')).toContainText('Triceps')
  await expect(page.getByText('Unlinked history remains valid progress evidence', { exact: false })).toBeVisible()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') {
    await page.locator('.muscle-plan-panel').screenshot({ path: 'output/playwright/muscle-plan-dose-mobile.png' })
    await page.screenshot({ path: 'output/playwright/muscle-dose-mobile.png', fullPage: true })
  }
  expect(browserErrors).toEqual([])
})

test('edits a custom movement without splitting history and blocks alias collisions', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Library' }).click()
  await page.getByRole('button', { name: 'Add movement' }).click()
  await page.getByLabel('Movement name').fill('Ring Press Arc')
  await page.getByLabel('Custom movement equipment').fill('rings, cable')
  await page.getByRole('button', { name: 'Create separate history' }).click()
  await page.getByRole('button', { name: 'Open movement' }).last().click()
  await page.getByRole('button', { name: 'Edit catalog' }).click()
  await expect(page.getByRole('heading', { name: 'Edit custom movement' })).toBeVisible()
  const openModalDimensions = await page.getByRole('dialog').evaluate((dialog) => ({ scrollWidth: dialog.scrollWidth, clientWidth: dialog.clientWidth }))
  expect(openModalDimensions.scrollWidth).toBeLessThanOrEqual(openModalDimensions.clientWidth)
  await page.getByLabel('Catalog movement name').fill('Low Incline Ring Press')
  await page.getByLabel('Catalog exercise family').fill('Incline Press')
  await page.getByLabel('Catalog equipment').fill('rings, cable')
  await page.getByLabel('Catalog aliases').fill('Bench')
  await page.getByLabel('Use athlete-reviewed muscle mapping').check()
  await page.getByLabel('Catalog direct muscle').selectOption('pectorals')
  await page.getByLabel('Catalog secondary Triceps').check()
  await page.getByLabel('Catalog edit reason').fill('Standardized the movement name and equipment')
  await page.getByRole('button', { name: 'Save without splitting history' }).click()
  await expect(page.getByRole('alert')).toContainText('already belongs to Competition Bench Press')
  if (testInfo.project.name === 'mobile-chromium') {
    await page.getByRole('dialog').evaluate((element) => { element.scrollTop = 0 })
    await page.getByRole('dialog').screenshot({ path: 'output/playwright/catalog-edit-mobile.png' })
    await page.locator('.muscle-map-editor').screenshot({ path: 'output/playwright/custom-muscle-mapping-mobile.png' })
  }
  await page.getByLabel('Catalog aliases').fill('Ring Incline')
  await page.getByRole('button', { name: 'Save without splitting history' }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Low Incline Ring Press' })).toBeVisible()
  await expect(page.getByText('Athlete-reviewed muscle dose')).toBeVisible()
  await expect(page.getByText('Direct · Pectorals')).toBeVisible()
  await expect(page.getByText('Secondary · Triceps')).toBeVisible()
  await page.getByRole('button', { name: 'Close Low Incline Ring Press' }).click()
  await expect(page.getByRole('heading', { name: 'History and catalog ledger' })).toBeVisible()
  await expect(page.getByText('muscle-dose mapping reviewed and updated', { exact: false })).toBeVisible()
  await expect(page.getByText('+0 volume', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Undo latest change' }).click()
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted?.state?.historyMutations?.at(-1)).toMatchObject({ type: 'exercise-edited' })
  expect(persisted?.state?.historyMutations?.at(-1)?.undoneAt).toBeTruthy()
  const restoredCustom = persisted?.state?.exercises?.find((exercise: { name: string; muscleMapping?: unknown }) => exercise.name === 'Ring Press Arc')
  expect(restoredCustom).toBeTruthy()
  expect(restoredCustom?.muscleMapping).toBeUndefined()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('documents intentional duplicates and merges a connected group in one decision', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Library' }).click()

  await page.getByRole('button', { name: 'Add movement' }).click()
  await page.getByLabel('Movement name').fill('Flat Barbell Bench')
  await page.getByLabel('Custom movement equipment').fill('barbell, bench, rack')
  await expect(page.getByRole('button', { name: 'Create documented variation' })).toBeDisabled()
  await page.getByLabel('Distinct movement reason').fill('Fixed touch point and setup from an older notebook')
  await page.getByRole('button', { name: 'Create documented variation' }).click()

  await page.getByRole('button', { name: 'Add movement' }).click()
  await page.getByLabel('Movement name').fill('Bench')
  await page.getByLabel('Custom movement equipment').fill('barbell, bench, rack')
  await expect(page.getByRole('button', { name: 'Create documented variation' })).toBeDisabled()
  await page.getByLabel('Distinct movement reason').fill('Temporary imported name that still needs cleanup')
  await page.getByRole('button', { name: 'Create documented variation' }).click()

  await page.getByRole('button', { name: 'Data quality (1)' }).click()
  await expect(page.getByText('3 connected identities')).toBeVisible()
  await page.getByRole('button', { name: 'Review group' }).click()
  await expect(page.getByRole('heading', { name: 'Merge duplicate movements' })).toBeVisible()
  await page.getByRole('radio', { name: /Keep Competition Bench Press/ }).click()
  await expect(page.getByRole('radio', { name: /Keep Competition Bench Press/ })).toHaveAttribute('aria-checked', 'true')
  if (testInfo.project.name === 'mobile-chromium') {
    await page.getByRole('dialog').evaluate((element) => { element.scrollTop = 0 })
    await page.getByRole('dialog').screenshot({ path: 'output/playwright/batch-duplicate-merge-mobile.png' })
  }
  await page.getByRole('button', { name: 'Merge 3 identities' }).click()
  await page.getByRole('button', { name: 'Data quality' }).click()
  await expect(page.getByText('No probable duplicates found')).toBeVisible()
  await page.getByRole('button', { name: 'Close Exercise data quality' }).click()

  const merged = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  const mergedCustom = merged?.state?.exercises?.filter((exercise: { custom?: boolean; name: string }) => exercise.custom && ['Bench', 'Flat Barbell Bench'].includes(exercise.name)) ?? []
  expect(mergedCustom).toHaveLength(2)
  expect(mergedCustom.every((exercise: { retired?: boolean; mergedIntoId?: string }) => exercise.retired && exercise.mergedIntoId === 'competition-bench')).toBe(true)
  expect(merged?.state?.historyMutations?.at(-1)).toMatchObject({ type: 'exercise-merged' })

  await page.getByRole('button', { name: 'Undo latest change' }).click()
  await expect(page.getByRole('button', { name: 'Data quality (1)' })).toBeVisible()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('separates linked plan completion from completed history with no stored plan', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: 'Finish workout without survey' }).click()
  await page.getByRole('button', { name: 'Progress' }).click()

  const dosePanel = page.locator('.dose-panel')
  await expect(dosePanel.getByRole('heading', { name: 'What was intended, what was linked, what remains unknown' })).toBeVisible()
  await expect(dosePanel.getByText('1 / 16', { exact: true })).toBeVisible()
  await expect(dosePanel.getByText('7 planned · 1 linked completed', { exact: false })).toBeVisible()
  await expect(dosePanel.getByText('Completed without stored plan')).toBeVisible()
  await expect(dosePanel.getByText('cannot be assigned to a missing plan', { exact: false })).toBeVisible()
  await expect(dosePanel.getByText('not a neglect label or a recommendation to add catch-up volume', { exact: false })).toBeVisible()
  const panelDimensions = await dosePanel.evaluate((panel) => ({ scrollWidth: panel.scrollWidth, clientWidth: panel.clientWidth }))
  expect(panelDimensions.scrollWidth).toBeLessThanOrEqual(panelDimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await dosePanel.screenshot({ path: 'output/playwright/planned-dose-mobile.png' })
  expect(browserErrors).toEqual([])
})

test('imports source-dated history only after canonical identity review and blocks re-import duplication', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Library' }).click()
  const baselineHistoryCount = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}').state.history.length)
  await page.getByRole('button', { name: 'Import history' }).click()
  const csv = 'date,exercise,load,reps,rir,session\n2025-04-02,Bench,205,5,2,Upper A\n2025-04-02,Bench,205,5,2,Upper A\n2025-04-02,Legacy Coffin,95,12,,Upper A\n'
  await page.getByLabel('Training history CSV').setInputFiles({ name: 'jb-notebook.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await expect(page.getByText('3', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('exact canonical or alias match')).toBeVisible()
  await expect(page.getByText('no deterministic match')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Import validated sets' })).toBeDisabled()
  await page.getByLabel('Map Legacy Coffin').selectOption('coffin-press')
  await expect(page.getByRole('button', { name: 'Import validated sets' })).toBeEnabled()
  const dialogDimensions = await page.getByRole('dialog').evaluate((dialog) => ({ scrollWidth: dialog.scrollWidth, clientWidth: dialog.clientWidth }))
  expect(dialogDimensions.scrollWidth).toBeLessThanOrEqual(dialogDimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') {
    await page.getByRole('dialog').screenshot({ path: 'output/playwright/history-import-preview-mobile.png' })
    await page.getByRole('dialog').evaluate((dialog) => dialog.scrollTo({ top: dialog.scrollHeight }))
    await page.getByRole('dialog').screenshot({ path: 'output/playwright/history-import-review-mobile.png' })
  }
  await page.getByRole('button', { name: 'Import validated sets' }).click()
  await expect(page.getByText('3 source sets imported and replayed.')).toBeVisible()
  await expect(page.getByText('3 completed sets imported from jb-notebook.csv.')).toBeVisible()

  let persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.state.history).toHaveLength(baselineHistoryCount + 3)
  expect(persisted.state.history.slice(-3).every((workSet: { qualityConfirmed: boolean }) => workSet.qualityConfirmed === false)).toBe(true)
  expect(persisted.state.history.at(-1)).toMatchObject({ exerciseId: 'coffin-press', originalExerciseName: 'Legacy Coffin', importSourceName: 'jb-notebook.csv', importRow: 4, rirKnown: false })

  await page.getByRole('button', { name: 'Import history' }).click()
  await page.getByLabel('Training history CSV').setInputFiles({ name: 'jb-notebook.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await expect(page.getByText('Already imported').locator('..').getByText('3', { exact: true })).toBeVisible()
  await page.getByLabel('Map Legacy Coffin').selectOption('coffin-press')
  await page.getByRole('button', { name: 'Import validated sets' }).click()
  await expect(page.getByText('No sets added. All 3 rows already exist from an earlier import.')).toBeVisible()
  persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.state.history).toHaveLength(baselineHistoryCount + 3)

  await page.getByRole('button', { name: 'Undo latest change' }).click()
  persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.state.history).toHaveLength(baselineHistoryCount)
  expect(persisted.state.historyMutations.at(-1)).toMatchObject({ type: 'history-imported' })
  expect(persisted.state.historyMutations.at(-1).undoneAt).toBeTruthy()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('turns imported exact history into athlete-reviewed placement evidence without silent inference', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.evaluate(() => {
    const persisted = JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}')
    persisted.state.history = []
    persisted.state.records = []
    persisted.state.historyMutations = []
    localStorage.setItem('forgepath-private-alpha-v1', JSON.stringify(persisted))
  })
  await page.reload()
  await page.getByRole('button', { name: 'Library' }).click()
  await page.getByRole('button', { name: 'Import history' }).click()
  const csv = [
    'date,exercise,load,reps,rir,session',
    '2026-08-01,Bench,185,5,2,Upper A', '2026-08-01,Bench,185,5,2,Upper A',
    '2026-08-04,Bench,190,5,2,Upper A', '2026-08-04,Bench,190,5,2,Upper A',
    '2026-08-07,Bench,195,5,2,Upper A', '2026-08-07,Bench,195,5,2,Upper A'
  ].join('\n')
  await page.getByLabel('Training history CSV').setInputFiles({ name: 'recent-bench.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: 'Import validated sets' }).click()
  const evidencePanel = page.locator('.placement-history-panel')
  await expect(evidencePanel).toContainText('Competition Bench Press')
  await expect(evidencePanel).toContainText('6 sets · 3 dates in 42 days')
  await expect(evidencePanel).toContainText('Evidence 4/5')
  await expect(evidencePanel).toContainText('Tolerance 3/5')
  await expect(evidencePanel).toContainText('6 recent imported sets remain numeric-only.')
  if (testInfo.project.name === 'mobile-chromium') {
    await page.getByRole('button', { name: 'Dismiss message' }).click()
    await page.locator('.bottom-nav').evaluate((element) => { (element as HTMLElement).style.display = 'none' })
    await evidencePanel.screenshot({ path: 'output/playwright/history-placement-evidence-mobile.png' })
  }

  await page.getByRole('button', { name: 'Review in placement' }).click()
  await expect(page.getByRole('heading', { name: 'Past experience is not current tolerance.' })).toBeVisible()
  await page.getByRole('button', { name: 'Competition Bench Press Recent evidence: 1' }).click()
  await page.getByRole('button', { name: 'Use evidence 4/5' }).click()
  await page.getByRole('button', { name: 'Use tolerance 3/5' }).click()
  await expect(page.getByRole('button', { name: 'Using evidence 4/5' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Using tolerance 3/5' })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') {
    await page.evaluate(() => (document.activeElement as HTMLElement | null)?.blur())
    await page.locator('.skip-link').evaluate((element) => { (element as HTMLElement).style.display = 'none' })
    await page.locator('.movement-placement-inputs').screenshot({ path: 'output/playwright/history-placement-review-mobile.png' })
  }
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: /Stable.*Consistent useful training/ }).click()
  await page.getByRole('button', { name: 'Schedule stability: 4' }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.locator('.movement-placement-preview')).toContainText('Exact history accepted for evidence + tolerance')
  await page.getByRole('button', { name: /This looks right.*Enter ForgePath/ }).click()
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.locator('.profile-movement-lanes')).toContainText('History reviewed')
  await expect(page.locator('.profile-movement-lanes')).toContainText('6 recent exact sets')
  if (testInfo.project.name === 'mobile-chromium') {
    await page.getByRole('button', { name: 'Dismiss message' }).click()
    await page.locator('.profile-movement-lanes details').filter({ hasText: 'Competition Bench Press' }).locator('summary').click()
    await page.locator('.placement-profile-evidence').screenshot({ path: 'output/playwright/history-placement-profile-mobile.png' })
  }

  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.version).toBe(17)
  expect(persisted.state.athlete.placement.ruleVersion).toBe('placement-v3')
  const benchInput = persisted.state.athlete.placement.inputs.movementProfiles.find((profile: { exerciseId: string }) => profile.exerciseId === 'competition-bench')
  const benchPlacement = persisted.state.athlete.placement.movementPlacements.find((placement: { exerciseId: string }) => placement.exerciseId === 'competition-bench')
  expect(benchInput).toMatchObject({ dataConfidence: 4, strengthTolerance: 3, historyReview: { acceptedFields: ['dataConfidence', 'strengthTolerance'], evidence: { ruleVersion: 'placement-history-v1', recentSetCount: 6, recentImportedSetCount: 6, suggestedDataConfidence: 4, suggestedStrengthTolerance: 3 } } })
  expect(benchPlacement).toMatchObject({ ruleVersion: 'movement-placement-v2', dataConfidence: 4, strengthTolerance: 3, historyReview: { evidence: { sourceSetIds: expect.arrayContaining(persisted.state.history.map((workSet: { id: string }) => workSet.id)) } } })
  const activePlan = persisted.state.mesocycles.find((plan: { id: string }) => plan.id === persisted.state.activeMesocycleId)
  const benchSession = persisted.state.sessions.find((session: { mesocycleId: string; exercises: Array<{ role: string; exerciseId: string }> }) => session.mesocycleId === activePlan.id && session.exercises.some((exercise) => exercise.role === 'primary' && exercise.exerciseId === 'competition-bench'))
  expect(activePlan.movementPlacements.find((placement: { exerciseId: string }) => placement.exerciseId === 'competition-bench')).toEqual(benchPlacement)
  expect(benchSession.generation.movementPlacement).toEqual(benchPlacement)
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('uses a saved location profile to gate unavailable work and executable load jumps', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)

  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByRole('heading', { name: 'Training locations' })).toBeVisible()
  await page.getByRole('button', { name: 'Add' }).click()
  await page.getByLabel('Equipment profile name').fill('Garage Rack')
  await page.getByLabel('Equipment profile type').selectOption('home-gym')
  await page.getByLabel('Available equipment').fill('barbell, bench, rack, plates, dumbbells')
  await page.getByLabel('Equipment constraints').fill('No cables\nNo selectorized machines')
  await page.getByLabel('barbell load increment').fill('2.5')
  await page.getByRole('button', { name: 'Save location' }).click()
  await page.getByRole('button', { name: /Garage Rack.*Use here/ }).click()
  await expect(page.getByRole('button', { name: /Garage Rack.*Active/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByRole('button', { name: /Garage Rack.*Active/ })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.equipment-profile-panel').screenshot({ path: 'output/playwright/equipment-profiles-mobile.png' })

  await page.getByRole('button', { name: 'Today' }).click()
  await expect(page.getByText('4 movements need equipment review')).toBeVisible()
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await expect(page.getByRole('heading', { name: 'Resolve equipment before logging' })).toBeVisible()
  await expect(page.getByRole('dialog').getByText('Two-Board Press')).toBeVisible()
  await page.getByRole('button', { name: 'Start and resolve movements' }).click()
  await expect(page.getByRole('heading', { name: 'Bench Powerbuilding Session' })).toBeVisible()
  await expect(page.getByText('Garage Rack · 4 to resolve')).toBeVisible()
  await expect(page.getByLabel('Set 1 load').first()).toHaveAttribute('step', '2.5')
  await expect(page.locator('.equipment-block')).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Blocked' }).first()).toBeDisabled()
  await page.locator('.equipment-block button').first().click()
  await expect(page.getByRole('heading', { name: 'Choose an educated replacement' })).toBeVisible()
  await expect(page.getByText('available at Garage Rack', { exact: false }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /Coffin Press/ })).toBeVisible()
  await page.getByRole('button', { name: /Coffin Press/ }).click()
  await expect(page.locator('.equipment-block')).toHaveCount(3)
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/equipment-gated-workout-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('filters the initial route queue through the selected training location', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()

  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: /Travel Setup/ }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByText('Generated for Travel Setup')).toBeVisible()
  await expect(page.locator('.route-equipment-preview')).toContainText('Competition Bench Press: barbell, bench, rack')
  await expect(page.locator('.route-equipment-preview')).toContainText('Protected anchors stay visible and require your review.')
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.route-equipment-preview').screenshot({ path: 'output/playwright/equipment-anchor-conflicts-mobile.png' })
  await page.getByRole('button', { name: 'Back' }).click()
  await page.getByRole('button', { name: /Home Gym/ }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByText('Generated for Home Gym')).toBeVisible()
  await expect(page.getByText('Loads use its lb increments.')).toBeVisible()
  await expect(page.getByText('route-session-v3', { exact: false })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.route-equipment-preview').screenshot({ path: 'output/playwright/equipment-aware-generation-preview-mobile.png' })
  await page.getByRole('button', { name: /This looks right.*Enter ForgePath/ }).click()
  await expect(page.getByRole('heading', { name: 'Your next useful win.' })).toBeVisible()
  await expect(page.getByText(/movements? need equipment review/)).toHaveCount(0)

  const generated = await page.evaluate(() => {
    const persisted = JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}')
    const state = persisted.state
    const profile = state.equipmentProfiles.find((candidate: { id: string }) => candidate.id === 'equipment-home-gym')
    const available = new Set(profile.equipment)
    const exerciseById = new Map(state.exercises.map((exercise: { id: string }) => [exercise.id, exercise]))
    const supportFits = state.sessions.every((session: { exercises: Array<{ exerciseId: string; role: string }> }) => session.exercises.filter((planned) => planned.role !== 'primary').every((planned) => {
      const exercise = exerciseById.get(planned.exerciseId) as { equipment: string[] }
      return exercise.equipment.every((item) => available.has(item))
    }))
    return {
      persistenceVersion: persisted.version,
      supportFits,
      ruleVersions: state.sessions.map((session: { generation?: { ruleVersion: string } }) => session.generation?.ruleVersion),
      profileIds: state.sessions.map((session: { generation?: { equipment?: { profileId: string } } }) => session.generation?.equipment?.profileId),
      planProfileId: state.mesocycles.find((plan: { id: string }) => plan.id === state.activeMesocycleId)?.generationEquipment?.profileId
    }
  })
  expect(generated).toMatchObject({ persistenceVersion: 17, supportFits: true, planProfileId: 'equipment-home-gym' })
  expect(generated.ruleVersions.every((value: string) => value === 'route-session-v3')).toBe(true)
  expect(generated.profileIds.every((value: string) => value === 'equipment-home-gym')).toBe(true)
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('builds an explainable multi-dimensional placement and preserves athlete control', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()

  await page.getByRole('button', { name: 'Strength', exact: true }).click()
  await page.getByLabel('Years of structured training').fill('8')
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: 'Movement skill: 5' }).click()
  await page.getByRole('button', { name: 'Intensity tolerance: 4' }).click()
  await page.getByRole('button', { name: 'Volume tolerance: 4' }).click()
  await page.getByRole('button', { name: 'Current evidence quality: 4' }).click()
  await page.getByRole('button', { name: 'Competition Back Squat Skill: 1' }).click()
  await page.getByRole('button', { name: 'Sumo Deadlift Recent evidence: 1' }).click()
  if (testInfo.project.name === 'mobile-chromium') {
    await page.evaluate(() => (document.activeElement as HTMLElement | null)?.blur())
    await page.locator('.skip-link').evaluate((element) => { (element as HTMLElement).style.display = 'none' })
    await page.locator('.movement-placement-inputs').screenshot({ path: 'output/playwright/movement-placement-input-mobile.png' })
  }
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: /Stable.*Consistent useful training/ }).click()
  await page.getByRole('button', { name: 'Schedule stability: 4' }).click()
  await page.getByRole('button', { name: /Continue/ }).click()

  await expect(page.getByRole('heading', { name: 'Direct Strength Development', exact: true })).toBeVisible()
  await expect(page.getByText('high confidence', { exact: true })).toBeVisible()
  await expect(page.getByText('Long-term experience remains an asset', { exact: false })).toBeVisible()
  await expect(page.getByText('Your starting sessions will actually change')).toBeVisible()
  await expect(page.getByText('4 × 4', { exact: true })).toBeVisible()
  await expect(page.locator('.movement-placement-preview')).toContainText('Competition Back Squat')
  await expect(page.locator('.movement-placement-preview')).toContainText('Introductory Skill Cycle')
  await expect(page.locator('.movement-placement-preview')).toContainText('Competition Bench Press')
  await expect(page.locator('.movement-placement-preview')).toContainText('Direct Strength Development')
  await expect(page.locator('.movement-placement-preview')).toContainText('Sumo Deadlift')
  await expect(page.locator('.movement-placement-preview')).toContainText('Bridge and Calibration Cycle')
  await page.getByText('Why not lower or higher?').click()
  await expect(page.getByText('Current experience and skill do not support resetting', { exact: false })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') {
    await page.evaluate(() => (document.activeElement as HTMLElement | null)?.blur())
    await page.locator('.skip-link').evaluate((element) => { (element as HTMLElement).style.display = 'none' })
    await page.locator('.onboarding__panel').screenshot({ path: 'output/playwright/onboarding-placement-mobile.png' })
  }

  await page.getByRole('button', { name: /Start more conservatively/ }).click()
  await expect(page.getByRole('heading', { name: 'Base-Building Cycle' })).toBeVisible()
  await expect(page.getByText('3 × 8', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /This looks right.*Enter ForgePath/ }).click()
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByText('Base-Building Cycle', { exact: true }).first()).toBeVisible()
  await expect(page.getByText(/high confidence.*placement-v3.*conservative/i)).toBeVisible()
  await expect(page.locator('.profile-movement-lanes')).toContainText('Competition Back Squat')
  await expect(page.locator('.profile-movement-lanes')).toContainText('Introductory Skill Cycle')
  await expect(page.locator('.profile-movement-lanes')).toContainText('Competition Bench Press')
  await expect(page.locator('.profile-movement-lanes')).toContainText('Base-Building Cycle')
  await expect(page.locator('.profile-movement-lanes')).toContainText('Sumo Deadlift')
  await expect(page.locator('.profile-movement-lanes')).toContainText('Reacclimation and Productive Work')
  await page.getByText('Why and how this will be verified').click()
  await expect(page.getByText(/first work sets/i)).toBeVisible()

  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.version).toBe(17)
  expect(persisted.state.athlete.placement).toMatchObject({ ruleVersion: 'placement-v3', recommendedRoute: 'strength', selectedRoute: 'base-building', confidence: 'high', decision: 'conservative' })
  expect(persisted.state.athlete.placement.movementPlacements.map((movement: { exerciseId: string; selectedRoute: string }) => [movement.exerciseId, movement.selectedRoute])).toEqual([
    ['competition-squat', 'introductory-skill'], ['competition-bench', 'base-building'], ['sumo-deadlift', 'reacclimation']
  ])
  expect(persisted.state.athlete.level.movementSkill).toBe(5)
  expect(persisted.state.mesocycles.find((plan: { id: string }) => plan.id === persisted.state.activeMesocycleId)).toMatchObject({ dominantAdaptation: 'reacclimation', title: 'Base-Building Cycle · Starting Cycle', entryRoute: 'base-building', generationRuleVersion: 'route-session-v3', generationEquipment: { profileId: 'equipment-commercial-gym' } })
  expect(new Set(persisted.state.sessions.map((session: { generation?: { route: string } }) => session.generation?.route))).toEqual(new Set(['introductory-skill', 'base-building', 'reacclimation']))
  expect(persisted.state.sessions.every((session: { generation?: { ruleVersion: string; planRoute?: string; equipment?: { profileId: string }; movementPlacement?: { exerciseId: string } }; exercises: Array<{ role: string; exerciseId: string }> }) => session.generation?.ruleVersion === 'route-session-v3' && session.generation.planRoute === 'base-building' && session.generation.equipment?.profileId === 'equipment-commercial-gym' && session.generation.movementPlacement?.exerciseId === session.exercises.find((exercise) => exercise.role === 'primary')?.exerciseId)).toBe(true)
  expect(persisted.state.sessions[0].exercises[0].sets[0]).toMatchObject({ targetReps: 8, targetRir: 3 })
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.settings-main .panel').first().screenshot({ path: 'output/playwright/placement-profile-mobile.png' })
  expect(browserErrors).toEqual([])
})

test('pauses automatic training when placement says pain changes movement choice', async ({ page }) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: /Changes what I can train/ }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByRole('heading', { name: 'Pain-Aware Modified Entry', exact: true })).toBeVisible()
  await expect(page.getByText('This is not medical clearance', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: /This looks right.*Enter ForgePath/ }).click()
  await expect(page.getByRole('heading', { name: 'The app learns. You stay in charge.' })).toBeVisible()
  await page.getByRole('button', { name: 'Today' }).click()
  await expect(page.getByText('Workout start paused for placement review')).toBeVisible()
  await expect(page.getByRole('button', { name: /Reassess before training/ })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Start without check-in' })).toBeDisabled()
  await page.getByRole('button', { name: 'You', exact: true }).click()
  await page.getByRole('button', { name: 'Reassess starting placement' }).click()
  await expect(page.getByRole('heading', { name: 'Build my starting profile' })).toBeVisible()
  await page.getByRole('button', { name: /Quick Start/ }).click()
  await expect(page.getByRole('heading', { name: 'Your next useful win.' })).toBeVisible()
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.state.mesocycles).toHaveLength(2)
  expect(persisted.state.mesocycles.filter((plan: { status: string }) => plan.status === 'active')).toHaveLength(1)
  expect(persisted.state.mesocycles.filter((plan: { status: string }) => plan.status === 'superseded')).toHaveLength(1)
  expect(persisted.state.athlete.placement).toMatchObject({ decision: 'quick-start', confidence: 'low' })
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('turns warm-up, first-set, session, and recovery evidence into an auditable placement check', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)

  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await expect(page.getByText('Competition Bench Press check 1 of 3')).toBeVisible()
  await page.getByRole('button', { name: 'As expected' }).click()
  await expect(page.getByText('Warm-up saved')).toBeVisible()
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: /Full.*10 questions/ }).click()
  await page.getByRole('button', { name: 'How difficult was the session overall?: 7' }).click()
  await page.getByRole('button', { name: 'How consistent was your technique?: 4' }).click()
  await page.getByRole('button', { name: 'Did any movement create joint pain or irritation?: 0' }).click()
  await page.getByRole('button', { name: 'How well did the session fit the time you had?: 4' }).click()
  await page.getByRole('button', { name: 'Save feedback & finish' }).click()
  await page.getByRole('button', { name: 'Today' }).click()
  await expect(page.getByText('How did you recover from Bench Powerbuilding Session?')).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.placement-recovery-check').screenshot({ path: 'output/playwright/placement-recovery-check-mobile.png' })
  await page.getByRole('button', { name: 'Recovered', exact: true }).click()
  await page.getByRole('button', { name: 'You', exact: true }).click()
  await expect(page.getByText('1 resolved · 1 productive checks across 1 exact lane', { exact: false })).toBeVisible()
  await expect(page.getByText('Starting route supported')).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.placement-profile-evidence').screenshot({ path: 'output/playwright/placement-verification-profile-mobile.png' })

  let persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.version).toBe(17)
  expect(persisted.state.placementVerifications).toHaveLength(1)
  expect(persisted.state.placementVerifications[0]).toMatchObject({ ruleVersion: 'placement-verification-v1', status: 'resolved', verdict: 'supports-route', warmupResponse: 'as-expected', recoveryResponse: 'recovered' })
  expect(persisted.state.history.some((workSet: { id: string }) => workSet.id === persisted.state.placementVerifications[0].firstSet.sourceSetId)).toBe(true)
  await page.reload()
  await page.getByRole('button', { name: 'You', exact: true }).click()
  await expect(page.getByText('Starting route supported')).toBeVisible()
  persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.state.placementVerifications[0].recoveryCapturedAt).toBeTruthy()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('requires placement review after painful productive verification without diagnosing the athlete', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await page.getByRole('button', { name: 'Painful' }).click()
  await expect(page.getByText('Warm-up saved')).toBeVisible()
  await expect(page.getByText('painful', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: 'Finish workout without survey' }).click()
  await page.getByRole('button', { name: 'Today' }).click()
  await expect(page.getByText('Workout start paused for placement review')).toBeVisible()
  await expect(page.getByText('A placement verification recorded pain that changed what could be trained.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: /Reassess before training/ })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Start without check-in' })).toBeDisabled()
  if (testInfo.project.name === 'mobile-chromium') {
    await page.locator('.skip-link').evaluate((element) => { (element as HTMLElement).style.display = 'none' })
    await page.locator('.hero-workout').screenshot({ path: 'output/playwright/placement-verification-pain-gate-mobile.png' })
  }
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.state.placementVerifications[0]).toMatchObject({ warmupResponse: 'painful', status: 'resolved', verdict: 'reassessment-required', firstSet: null })
  expect(persisted.state.athlete.placement.selectedRoute).not.toBe('pain-aware-modified')
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('turns repeated productive checks into an athlete-reviewed placement checkpoint without silent reclassification', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)

  const completeSupportiveCheck = async (sequence: number) => {
    await page.getByRole('button', { name: 'Start without check-in' }).click()
    await expect(page.getByText(new RegExp(`check ${sequence} of 3$`))).toBeVisible()
    await page.getByRole('button', { name: 'As expected' }).click()
    await page.getByRole('button', { name: 'Log set' }).first().click()
    await page.getByRole('button', { name: 'Finish workout' }).click()
    await page.getByRole('button', { name: /Full.*10 questions/ }).click()
    await page.getByRole('button', { name: 'How difficult was the session overall?: 7' }).click()
    await page.getByRole('button', { name: 'How consistent was your technique?: 4' }).click()
    await page.getByRole('button', { name: 'Did any movement create joint pain or irritation?: 0' }).click()
    await page.getByRole('button', { name: 'How well did the session fit the time you had?: 4' }).click()
    await page.getByRole('button', { name: 'Save feedback & finish' }).click()
    await page.getByRole('button', { name: 'Today' }).click()
    await page.getByRole('button', { name: 'Recovered', exact: true }).click()
  }

  await completeSupportiveCheck(1)
  await completeSupportiveCheck(1)

  await expect(page.locator('.placement-exit-callout')).toContainText('Your current route has earned confirmation.')
  if (testInfo.project.name === 'mobile-chromium') await page.locator('.placement-exit-callout').screenshot({ path: 'output/playwright/placement-exit-checkpoint-mobile.png' })
  await page.locator('.placement-exit-callout').click()
  const dismissNotice = page.getByRole('button', { name: 'Dismiss message' })
  if (await dismissNotice.isVisible()) await dismissNotice.click()
  const checkpoint = page.locator('.placement-exit-panel')
  await expect(checkpoint).toContainText('Confirm current route')
  await expect(checkpoint.locator('.placement-exit-criterion--met')).toHaveCount(4)
  await expect(checkpoint).toContainText('2 resolved plan-route checks')
  if (testInfo.project.name === 'mobile-chromium') await checkpoint.screenshot({ path: 'output/playwright/placement-exit-profile-mobile.png' })
  await checkpoint.getByRole('button', { name: 'Review criterion outcome' }).click()
  await expect(page.getByRole('heading', { name: 'Review placement checkpoint' })).toBeVisible()
  await expect(page.locator('.placement-exit-choice-list button').first()).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Why is this the right decision now?').fill('Both source-linked sessions matched the expected effort, technique stayed stable, and recovery was normal.')
  await page.getByRole('button', { name: 'Save checkpoint decision' }).click()
  await expect(checkpoint).toContainText('Saved athlete review')
  await expect(checkpoint.getByRole('button', { name: 'Current evidence reviewed' })).toBeDisabled()

  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.version).toBe(17)
  expect(persisted.state.placementExitReviews).toHaveLength(1)
  expect(persisted.state.placementExitReviews[0]).toMatchObject({
    ruleVersion: 'placement-exit-review-v1',
    decision: 'continue-current',
    assessment: { ruleVersion: 'placement-exit-v1', recommendation: 'confirm-current', resolved: 2, supports: 2, excludedDifferentRouteChecks: 0 }
  })
  expect(persisted.state.placementExitReviews[0].assessment.sourceVerificationEvents).toHaveLength(2)
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('keeps productive checkpoints independent per exact movement and saves the athlete lane decision', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)

  await page.evaluate(() => {
    const key = 'forgepath-private-alpha-v1'
    const persisted = JSON.parse(localStorage.getItem(key) ?? '{}')
    const first = persisted.state.sessions[0]
    const repeat = structuredClone(first)
    repeat.id = `${first.id}-repeat`
    repeat.title = 'Bench Powerbuilding Repeat'
    repeat.dayLabel = 'Queued exact-lane check'
    repeat.exercises = repeat.exercises.map((planned: { id: string; sets: Array<{ id: string }> }) => ({
      ...planned,
      id: `${planned.id}-repeat`,
      sets: planned.sets.map((workSet) => ({ ...workSet, id: `${workSet.id}-repeat` }))
    }))
    persisted.state.sessions.splice(1, 0, repeat)
    const plan = persisted.state.mesocycles.find((candidate: { id: string }) => candidate.id === persisted.state.activeMesocycleId)
    plan.sessionIds = [first.id, repeat.id, ...plan.sessionIds.filter((id: string) => id !== first.id)]
    localStorage.setItem(key, JSON.stringify(persisted))
  })
  await page.reload()

  const completeBenchCheck = async (sequence: number) => {
    await page.getByRole('button', { name: 'Start without check-in' }).click()
    await expect(page.getByText(`Competition Bench Press check ${sequence} of 3`)).toBeVisible()
    await page.getByRole('button', { name: 'As expected' }).click()
    await page.getByRole('button', { name: 'Log set' }).first().click()
    await page.getByRole('button', { name: 'Finish workout' }).click()
    await page.getByRole('button', { name: /Full.*10 questions/ }).click()
    await page.getByRole('button', { name: 'How difficult was the session overall?: 7' }).click()
    await page.getByRole('button', { name: 'How consistent was your technique?: 4' }).click()
    await page.getByRole('button', { name: 'Did any movement create joint pain or irritation?: 0' }).click()
    await page.getByRole('button', { name: 'How well did the session fit the time you had?: 4' }).click()
    await page.getByRole('button', { name: 'Save feedback & finish' }).click()
    await page.getByRole('button', { name: 'Today' }).click()
    await page.getByRole('button', { name: 'Recovered', exact: true }).click()
  }

  await completeBenchCheck(1)
  await completeBenchCheck(2)
  const movementCallout = page.locator('.movement-exit-callout')
  await expect(movementCallout).toContainText('Competition Bench Press has an independent lane checkpoint.')
  if (testInfo.project.name === 'mobile-chromium') await movementCallout.screenshot({ path: 'output/playwright/movement-exit-checkpoint-mobile.png' })
  await movementCallout.click()
  const lane = page.locator('.movement-lane-card').filter({ hasText: 'Competition Bench Press' })
  await lane.locator('summary').click()
  await expect(lane).toContainText('Confirm current route')
  await expect(lane).toContainText('2/3 exact checks')
  await lane.getByRole('button', { name: 'Review movement lane' }).click()
  await expect(page.getByRole('heading', { name: 'Review Competition Bench Press lane' })).toBeVisible()
  await expect(page.locator('.movement-exit-review .placement-exit-criterion--met')).toHaveCount(4)
  if (testInfo.project.name === 'mobile-chromium') await page.getByRole('dialog').screenshot({ path: 'output/playwright/movement-exit-review-mobile.png' })
  await page.getByLabel('Why is this the right decision for Competition Bench Press?').fill('Two exact bench exposures matched target effort and recovered normally, so I am keeping this lane.')
  await page.getByRole('button', { name: 'Save movement decision' }).click()
  await expect(lane).toContainText('Athlete decision: continue current')
  await expect(lane.getByRole('button', { name: 'Current lane evidence reviewed' })).toBeDisabled()

  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted.version).toBe(17)
  expect(persisted.state.movementPlacementExitReviews).toHaveLength(1)
  expect(persisted.state.movementPlacementExitReviews[0]).toMatchObject({
    ruleVersion: 'movement-placement-exit-review-v1', exerciseId: 'competition-bench', decision: 'continue-current',
    assessment: { ruleVersion: 'movement-placement-exit-v1', exerciseId: 'competition-bench', resolved: 2, supports: 2 }
  })
  expect(persisted.state.movementPlacementExitReviews[0].assessment.sourceVerificationEvents.filter((event: { movementPlacement?: { exerciseId: string } }) => event.movementPlacement?.exerciseId === 'competition-bench').map((event: { sequence: number }) => event.sequence)).toEqual([1, 2])
  expect(persisted.state.athlete.placement.movementPlacements.find((movement: { exerciseId: string }) => movement.exerciseId === 'competition-bench').selectedRoute).toBe('powerbuilding')
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})
