import { expect, test } from '@playwright/test'

async function enterRecommendedProfile(page: import('@playwright/test').Page) {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: 'Use the recommended profile and start now' }).click()
  await expect(page.getByRole('heading', { name: 'Your next useful win.' })).toBeVisible()
}

test('validates an athlete-controlled PR without changing the prescription', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await expect(page.getByRole('heading', { name: 'Bench Strength + Upper Body' })).toBeVisible()
  await expect(page.getByText('Productive hold:', { exact: false }).first()).toBeVisible()

  const firstLoad = page.getByLabel('Set 1 load').first()
  await firstLoad.fill('185')
  await expect(page.getByText('Productive hold:', { exact: false }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await expect(page.getByText('Provisional until the workout is finished and saved.').first()).toBeVisible()

  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: /Full.*10 questions/ }).click()
  await page.getByRole('button', { name: 'How consistent was your technique?: 4' }).click()
  await page.getByRole('button', { name: 'Did any movement create joint pain or irritation?: 0' }).click()
  await page.getByRole('button', { name: 'Save feedback & finish' }).click()
  await expect(page.getByRole('heading', { name: 'PRs and micro wins' })).toBeVisible()
  await expect(page.getByText('Strength PR').first()).toBeVisible()
  await expect(page.getByText('185 heaviest completed load', { exact: false }).first()).toBeVisible()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/progress-achievements-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('keeps achievement controls optional and mobile layouts contained', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByRole('heading', { name: 'Achievement controls' })).toBeVisible()
  const quietMode = page.getByRole('checkbox', { name: 'Quiet mode' })
  await quietMode.check()
  await page.reload()
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByRole('checkbox', { name: 'Quiet mode' })).toBeChecked()

  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/gamification-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('explains a protected-primary substitution and preserves its outcome evidence', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await page.getByRole('button', { name: 'Change' }).first().click()
  await page.getByLabel('Substitution reason').selectOption('equipment')
  await page.getByRole('button', { name: /Coffin Press/ }).click()
  await expect(page.getByRole('alert')).toContainText('Confirm the protected-primary tradeoff')
  await page.getByRole('checkbox', { name: 'Confirm primary-anchor change' }).check()
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/substitution-picker-mobile.png', fullPage: true })
  await page.getByRole('button', { name: /Coffin Press/ }).click()
  await expect(page.getByText('Baseline calibration', { exact: true })).toBeVisible()
  await expect(page.getByText("The replaced movement's load was not copied", { exact: false })).toBeVisible()
  await page.getByLabel('Set 1 load').first().fill('40')
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: 'Finish workout without survey' }).click()
  await page.getByRole('button', { name: 'Library' }).click()
  await expect(page.getByRole('heading', { name: 'Exercise substitution ledger' })).toBeVisible()
  await expect(page.getByText('Competition Bench Press', { exact: false }).last()).toBeVisible()
  await expect(page.getByText('Coffin Press', { exact: false }).last()).toBeVisible()
  await expect(page.getByText('1 completed source set', { exact: false })).toBeVisible()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/substitution-ledger-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('honors minimal and off survey preferences without inventing answers', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'You' }).click()
  await page.getByLabel('Pre-session check-in mode').selectOption('minimal')
  await page.getByLabel('Post-session feedback mode').selectOption('off')
  await page.getByRole('button', { name: 'Today' }).click()
  await page.getByRole('button', { name: 'Minimal check-in & start' }).click()
  await expect(page.getByRole('heading', { name: 'Minimal readiness check' })).toBeVisible()
  await expect(page.locator('.survey-question')).toHaveCount(3)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/minimal-readiness-mobile.png', fullPage: true })
  await page.locator('.survey-question').first().getByRole('button', { name: 'Not sure' }).click()
  await page.getByRole('button', { name: 'Any soreness, aches, or pain affecting movement?: 0' }).click()
  await page.getByLabel('How many minutes do you actually have?').fill('45')
  await page.getByRole('button', { name: 'Use my check-in' }).click()
  await expect(page.getByText('low survey confidence')).toBeVisible()
  await expect(page.getByText('45 minute version')).toBeVisible()
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await expect(page.getByRole('heading', { name: 'PRs and micro wins' })).toBeVisible()
  await page.getByRole('button', { name: 'You' }).click()
  await expect(page.getByLabel('Post-session feedback mode')).toHaveValue('off')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  const surveys = persisted?.state?.surveys ?? []
  expect(surveys.at(-2)).toMatchObject({ type: 'pre', mode: 'minimal', answeredCount: 2, unknownCount: 1, confidence: 'low' })
  expect(surveys.at(-1)).toMatchObject({ type: 'post', mode: 'off', skipped: true, answeredCount: 0, unknownCount: 0, confidence: 'low' })
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/survey-preferences-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('defers optional feedback without blocking training and replays quality evidence later', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Start without check-in' }).click()
  await page.getByLabel('Set 1 load').first().fill('185')
  await page.getByRole('button', { name: 'Log set' }).first().click()
  await page.getByRole('button', { name: 'Finish workout' }).click()
  await page.getByRole('button', { name: /Minimal.*3 essential questions/ }).click()
  await page.getByRole('button', { name: 'Remind me later' }).click()
  await expect(page.getByRole('heading', { name: 'PRs and micro wins' })).toBeVisible()
  await expect(page.getByText('Unverified number best').first()).toBeVisible()

  await page.getByRole('button', { name: 'Today' }).click()
  await expect(page.getByLabel('Optional session feedback')).toBeVisible()
  await expect(page.getByRole('button', { name: /check-in & start|Start workout now/ })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/deferred-feedback-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Add feedback' }).click()
  await expect(page.getByRole('heading', { name: 'Optional Minimal session feedback' })).toBeVisible()
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/deferred-feedback-form-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'How difficult was the session overall?: 7' }).click()
  await page.getByRole('button', { name: 'How consistent was your technique?: 4' }).click()
  await page.getByRole('button', { name: 'Did any movement create joint pain or irritation?: 0' }).click()
  await page.getByRole('button', { name: 'Save feedback' }).click()
  await expect(page.getByLabel('Optional session feedback')).toHaveCount(0)
  await page.getByRole('button', { name: 'Progress' }).click()
  await expect(page.getByText('Strength PR').first()).toBeVisible()
  await expect(page.getByText('185 heaviest completed load', { exact: false }).first()).toBeVisible()

  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted?.version).toBe(8)
  expect(persisted?.state?.deferredFeedback?.at(-1)).toMatchObject({ mode: 'minimal', status: 'completed' })
  expect(persisted?.state?.deferredFeedback?.at(-1)?.surveyId).toBeTruthy()
  expect(persisted?.state?.history?.filter((workSet: { sessionId: string }) => workSet.sessionId === persisted.state.deferredFeedback.at(-1).sessionId).every((workSet: { qualityConfirmed?: boolean }) => workSet.qualityConfirmed === true)).toBe(true)
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})

test('shows calendar-quarter progress, exact movement mix, and honest priority attention', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Progress' }).click()
  await page.getByRole('button', { name: 'Qtr' }).click()
  await expect(page.getByRole('heading', { name: 'Monthly volume load' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'What filled this window' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Goal-relative completed evidence' })).toBeVisible()
  await expect(page.getByText('share of selected-period volume load, not share of hypertrophy stimulus or enjoyment', { exact: false })).toBeVisible()
  await expect(page.getByText('does not declare a body part neglected without a planned-dose model', { exact: false })).toBeVisible()
  await expect(page.locator('.progress-range button')).toHaveCount(7)
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  if (testInfo.project.name === 'mobile-chromium') await page.screenshot({ path: 'output/playwright/quarter-movement-mix-mobile.png', fullPage: true })
  expect(browserErrors).toEqual([])
})

test('edits a custom movement without splitting history and blocks alias collisions', async ({ page }, testInfo) => {
  const browserErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') browserErrors.push(message.text()) })
  page.on('pageerror', (error) => browserErrors.push(error.message))
  await enterRecommendedProfile(page)
  await page.getByRole('button', { name: 'Library' }).click()
  await page.getByRole('button', { name: 'Add movement' }).click()
  await page.getByLabel('Movement name').fill('Ring Press Arc')
  await page.getByRole('button', { name: 'Create separate history' }).click()
  await page.getByRole('button', { name: 'Open movement' }).last().click()
  await page.getByRole('button', { name: 'Edit catalog' }).click()
  await expect(page.getByRole('heading', { name: 'Edit custom movement' })).toBeVisible()
  const openModalDimensions = await page.getByRole('dialog').evaluate((dialog) => ({ scrollWidth: dialog.scrollWidth, clientWidth: dialog.clientWidth }))
  expect(openModalDimensions.scrollWidth).toBeLessThanOrEqual(openModalDimensions.clientWidth)
  await page.getByLabel('Catalog movement name').fill('Low Incline Ring Press')
  await page.getByLabel('Catalog exercise family').fill('Incline Press')
  await page.getByLabel('Catalog equipment').fill('rings, cable')
  await page.getByLabel('Catalog aliases').fill('Bench')
  await page.getByLabel('Catalog edit reason').fill('Standardized the movement name and equipment')
  await page.getByRole('button', { name: 'Save without splitting history' }).click()
  await expect(page.getByRole('alert')).toContainText('already belongs to Competition Bench Press')
  if (testInfo.project.name === 'mobile-chromium') {
    await page.getByRole('dialog').evaluate((element) => { element.scrollTop = 0 })
    await page.getByRole('dialog').screenshot({ path: 'output/playwright/catalog-edit-mobile.png' })
  }
  await page.getByLabel('Catalog aliases').fill('Ring Incline')
  await page.getByRole('button', { name: 'Save without splitting history' }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Low Incline Ring Press' })).toBeVisible()
  await page.getByRole('button', { name: 'Close Low Incline Ring Press' }).click()
  await expect(page.getByRole('heading', { name: 'History and catalog ledger' })).toBeVisible()
  await expect(page.getByText('catalog identity updated to Low Incline Ring Press', { exact: false })).toBeVisible()
  await expect(page.getByText('+0 volume', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Undo latest change' }).click()
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('forgepath-private-alpha-v1') ?? '{}'))
  expect(persisted?.state?.historyMutations?.at(-1)).toMatchObject({ type: 'exercise-edited' })
  expect(persisted?.state?.historyMutations?.at(-1)?.undoneAt).toBeTruthy()
  expect(persisted?.state?.exercises?.find((exercise: { name: string }) => exercise.name === 'Ring Press Arc')).toBeTruthy()
  const dimensions = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }))
  expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.clientWidth)
  expect(browserErrors).toEqual([])
})
